### ISSUE TITLE
Redirecting traffic to a remote SSLSPLIT instance

### ISSUE THREAD

**Issue by abduct** [droe/sslsplit#100]
I am trying to setup a remote SSLSPLIT instance on a server in which a wireless access point redirects its traffic to a server on another network (or server in the lan) for parsing/splitting.

A pictorial view that will hopefully make this clear:

![pic](https://cloud.githubusercontent.com/assets/5516806/8262593/3182d6cc-1688-11e5-9709-b232fb7bf707.png)

In the first sequence (black is outgoing traffic, red is incoming traffic) I have a LAN server running SSLSPLIT and I am wanting to redirect the traffic from the wireless AP to it for analyzing.

In the second sequence (black is outgoing traffic, red is incoming traffic, blue is the path traffic actually takes...) I want the wireless access point redirecting traffic to a remote server in another network (datacenter) to a server running SSLSPLIT.

In order to try to achieve this I have tried using iptables on the WIRELESS ACCESS POINT to redirect the traffic to the SSLSPLIT server.

```
iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination 192.168.0.198:8880
iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT --to-destination 192.168.0.198:8443
iptables -t nat -A POSTROUTING -j MASQUERADE
```
192.168.0.198 is the server running SSLSPLIT in the LAN configuration.

It appears this successfully sends the traffic, but the SSLSPLIT application goes into an infinite loop and exhausts all file descriptors causing it to shut down (192.168.0.198 is the servers IP running SSLSPLIT, 192.168.0.104 is the wireless access point). SSLSPLIT is ran like so: 

```
sudo ./sslsplit.bin -D -l connections.log -j ./ssl -S logdir/ -k ca.key -c ca.crt ssl 0.0.0.0 8443 tcp 0.0.0.0 8880
```

And this is the result once traffic starts being redirected:

```
**SNIP**
Initialized 4 connection handling threads
Started 4 connection handling threads
Starting main event loop.
Connecting to [192.168.0.198]:8880
Connecting to [192.168.0.198]:8880
tcp [192.168.0.104]:34796 [192.168.0.198]:8880
TCP connected to [192.168.0.198]:8880
TCP connected from [192.168.0.104]:34796
tcp [192.168.0.198]:57367 [192.168.0.198]:8880
TCP connected to [192.168.0.198]:8880
TCP connected from [192.168.0.198]:57367
Connecting to [192.168.0.198]:8880
Connecting to [192.168.0.198]:8880
tcp [192.168.0.198]:57368 [192.168.0.198]:8880
TCP connected to [192.168.0.198]:8880
TCP connected from [192.168.0.198]:57368
Connecting to [192.168.0.198]:8880
tcp [192.168.0.198]:57369 [192.168.0.198]:8880
TCP connected to [192.168.0.198]:8880
TCP connected from [192.168.0.198]:57369
tcp [192.168.0.104]:34797 [192.168.0.198]:8880
TCP connected to [192.168.0.198]:8880
TCP connected from [192.168.0.104]:34797
Connecting to [192.168.0.198]:8880
Connecting to [192.168.0.198]:8880
tcp [192.168.0.198]:57370 [192.168.0.198]:8880
TCP connected to [192.168.0.198]:8880
TCP connected from [192.168.0.198]:57370
Connecting to [192.168.0.198]:8880
tcp [192.168.0.198]:57371 [192.168.0.198]:8880
TCP connected to [192.168.0.198]:8880
TCP connected from [192.168.0.198]:57371
Connecting to [192.168.0.198]:8880
tcp [192.168.0.198]:57372 [192.168.0.198]:8880
TCP connected to [192.168.0.198]:8880
TCP connected from [192.168.0.198]:57372
**SNIP**
Failed to open 'logdir//20150619T202755Z-[192.168.0.198]:57762-[192.168.0.198]:8880.log': Too many open files (24)
tcp [192.168.0.198]:57762 [192.168.0.198]:8880
TCP connected to [192.168.0.198]:8880
TCP connected from [192.168.0.198]:57762
Error 24 on listener: Too many open files
Main event loop stopped.
Error from bufferevent: 104:Connection reset by peer 0:0:-:0:-:0:-
TCP disconnected to [192.168.0.198]:8880
TCP disconnected from [192.168.0.198]:57762
TCP disconnected to [192.168.0.198]:8880
TCP disconnected from [192.168.0.198]:57760
```
Is there documentation or a way to setup SSLSPLIT in such a remote server setup such as this? Is this a problem with my iptables rules? Do I need a server side rule on the server running SSLSPLIT to prevent it from connecting to itself? Do I need some sort of extra client side rule on the wireless access point? Is iptables able to handle such a redirect?

I've noticed that other transparent proxies have the exact same issue so I am sure it is not a software issue but rather a iptables/setup issue of the environment.

Thanks for any help.

**Comment by droe** [comment]
If you DNAT connections to a separate system, sslsplit on that separate system will see connections to [192.168.0.198]:8880, and thus, connect to itself. You have to run sslsplit on the same system that does the traffic redirection using either REDIRECT or TPROXY.

If you want to run sslsplit on a different server, you may be able to route (not DNAT!) the traffic to the box running sslsplit. The latter would then have a regular REDIRECT or TPROXY setup. Check online documentation on advanced routing setups using `ip route`.
