### ISSUE TITLE
Memory leak from ssl_x509_fingerprint()

### ISSUE THREAD

**Issue by scotloach** [droe/sslsplit#103]
On the develop branch, pxyconn.c:pxy_debug_crt()
This fpr variable:
fpr = ssl_x509_fingerprint(crt, 1)
is never freed.

It's possible other calls to this function are also never freed, e.g. from pxy_srccert_create() and pxy_ossl_servername_cb().

**Comment by droe** [comment]
The other invocations you mention should be freed when the respective ctx struct is freed. Please do object in case you disagree with this (somewhat rushed) analysis.
Thanks for reporting the memory leak!
