### ISSUE TITLE
sslsplit detectable by chrome

### ISSUE THREAD

**Issue by ranasikandar** [droe/sslsplit#107]
chrome detect mitm attack and stop victim for further, with showing a warning In chrome browser

**Comment by droe** [comment]
This is not a surprise, but FWIW: Can you be more specific, such as which site, server certificate, exact browser warning etc?

**Comment by freman** [comment]
Also, did you remember to install the CA certificate into chrome?

**Comment by ranasikandar** [comment]
i didn't install Ca into Chrome, wonder how to remotely install Ca to Chrome,

**Comment by droe** [comment]
Well, if you didn't install the CA into Chrome or the OS certificate store, then obviously Chrome will detect a MitM attack; this is supposed to happen and not a mistake.
