### ISSUE TITLE
EV_READ event re-enable bug

### ISSUE THREAD

**Issue by eunsoopark** [droe/sslsplit#109]
Hi. 

I found EV_READ event re-enable bug.

In pxy_bev_readcb(), if out buffer length >= OUTBUF_LIMIT, disable EV_READ event.

And enable EV_READ event in pxy_bev_writecb(), if out buffer length > 0.

In my case, out buffer length is always 0 when pxy_bev_writecb() is called and does not re-enabled EV_READ event.

I patch this bug. Check please.

```patch
--- pxyconn.c.org   2015-10-20 10:52:58.529801747 +0900
+++ pxyconn.c   2015-10-20 10:53:57.034603056 +0900
@@ -1612,15 +1612,17 @@
    }
 #endif /* DEBUG_PROXY */

-   struct evbuffer *outbuf = bufferevent_get_output(bev);
-   if (evbuffer_get_length(outbuf) > 0) {
+   if (!(bufferevent_get_enabled(other->bev) & EV_READ)) {
        /* data source temporarily disabled;
         * re-enable and reset watermark to 0. */
        bufferevent_setwatermark(bev, EV_WRITE, 0, 0);
        if (!other->closed) {
            bufferevent_enable(other->bev, EV_READ);
        }
-   } else if (other->closed) {
+   }
+
+   struct evbuffer *outbuf = bufferevent_get_output(bev);
+   if (evbuffer_get_length(outbuf) == 0 && other->closed) {
        /* finished writing and other end is closed;
         * close this end too and clean up memory */
        bufferevent_free_and_close_fd(bev, ctx);
```

**Comment by droe** [comment]
Thank you, good catch, committed to `develop`. This fix might actually have a positive impact on #18 too.

**Comment by eunsoopark** [comment]
I found bug of this patch.

In some case, other->bev can be NULL.

'''patch
--- pxyconn.c.org   2015-11-06 14:53:40.708333363 +0900
+++ pxyconn.c   2015-11-06 14:53:52.674086702 +0900
@@ -1611,7 +1611,7 @@
    }
 #endif /* DEBUG_PROXY */

-   if (!(bufferevent_get_enabled(other->bev) & EV_READ)) {
+   if (other->bev && !(bufferevent_get_enabled(other->bev) & EV_READ)) {
        /* data source temporarily disabled;
         * re-enable and reset watermark to 0. */
        bufferevent_setwatermark(bev, EV_WRITE, 0, 0);
'''
