### ISSUE TITLE
why the size of ssl log is 0?

### ISSUE THREAD

**Issue by leon-pku** [droe/sslsplit#111]
I use sslsplit to sniffer the data transfering using ssl, however, I've found out most of logs ending with 443.log is empty, why? any solutions?

**Comment by kdawes** [comment]
Pretty tough to solve this without some more information.  

How are you invoking sslsplit ?  What does your setup look like ?

**Comment by droe** [comment]
Please post the debug log, what kind of connections cause empty logs, how you invoke sslsplit, and the output of `sslsplit -V`.

**Comment by droe** [comment]
Over three months no response, closing issue, feel free to re-open or comment if this is still an issue for you.
