### ISSUE TITLE
Questions around content log to named pipe

### ISSUE THREAD

**Issue by mattes** [droe/sslsplit#112]
I have some questions around the full content log when using a named pipe.

1. I have a fundamental question regarding named pipes. If SSLsplit crashes __and restarts__, what will happen to the pipe? Will SSLsplit discard existing data in the pipe/ create a new pipe?
2. If I understand [log2pcap.py#L185](https://github.com/droe/sslsplit/blob/02ab680b34e95826bbb07e9bf922d1315e472b04/extra/log2pcap.py#L185) correctly, PCAPs will be finalized/closed after 60 seconds. Is there a better way to detect when there is no more data coming (because the TCP connection was closed)?
3. Is my observation correct, that chunked data isn't ordered by TCP connections?

I hope my questions make sense and are precise. It would be awesome if someone could give me feedback on this! Cheers!

**Comment by droe** [comment]
1. SSLsplit does not restart after a crash unless you wrap it in a script that does; what happens would be up to your script, subject to standard behaviour of your platform when a process writing to a pipe receives a SIGSEGV.
 1. With the current log format, no. You could modify the log format to also log the closing of connections, but that would break currently existing parsers of the logs so I would not want to do that without good reason or a backwards compatible log format choosing mechanism.
 1. Not sure what you are expecting exactly. Why should HTTP chunked encoding be re-ordered?

**Comment by droe** [comment]
Assuming answered, if still relevant please open separate issues per problem/bug.
