### ISSUE TITLE
sslsplit uses it's own IP for upstream requests

### ISSUE THREAD

**Issue by david-holonet** [droe/sslsplit#118]
Use sslsplit with the mode of tproxy, and find that sslsplit send request to server with its own IP as source. I read codes, and find that no operation is done when connecting to real server.

Here is my command:
`sslsplit -e tproxy -d tcp 0.0.0.0 8081`

iptables -t mangle -N DIVERT
iptables -t mangle -A PREROUTING -p tcp -m socket -j DIVERT
iptables -t mangle -A DIVERT -j MARK --set-xmark 0x${MARK_ID}/0xffffffff
iptables -t mangle -A DIVERT -j ACCEPT
MARK_ID=1
RULE_TID=200
PORTS=80
PLAIN_PORT=8081
iptables -t mangle -A PREROUTING -p tcp -m tcp --dport ${PORTS} -j TPROXY --on-port ${PLAIN_PORT} --tproxy-mark ${MARK_ID}
ip rule add fwmark ${MARK_ID} table ${RULE_TID}
ip route add local default dev lo table ${RULE_TID}

**Comment by droe** [comment]
That is expected. If the manual page is not clear enough on this, I am happy to take a pull request against the current `develop` branch in order to clarify the manual page wording.

**Comment by david-holonet** [comment]
Thanks for reply so soon. I got it.
