### ISSUE TITLE
How to ensure sslsplit uses ECDH key exchange?

### ISSUE THREAD

**Issue by curioustwo** [droe/sslsplit#119]
Hi!

When using sslsplit I am getting notice in Chrome browser saying the web site is using an obsolete cipher suite. This is due to the key exchange mechanism being RSA. How can I force sslsplit to use ECDH key exchange to satisfy Chrome browser? I don['t see an command line option allowing me to chose key exchange mechanism.

Thanks!

**Comment by droe** [comment]
The options `-s` and possibly `-r` and `-R` are your friends, see the manual page.

**Comment by droe** [comment]
Workaround: Use -g and -G appropriately. I will commit a fix that enables full-strength DHE and ECDHE by default to develop soon.
