### ISSUE TITLE
Building on BackTrack 5R3 fails to find libevent 2.x

### ISSUE THREAD

**Issue by doadam2** [droe/sslsplit#12]
I'm running BackTrack 5 R3 and trying to compile it.
I'm having an error about libevent. I tried updating it and currently libevent is in the newest version (apt-get).

When trying to compile SSLSplit I get the following error:

 root@bt:~/sslsplit# make
GNUmakefile:175: **\* dependency 'libevent 2.x' not found; install it or point LIBEVENT_BASE to base path.  Stop.

libevent is at '/usr/lib/libevent.a', and I have no idea how to set LIBEVENT_BASE appropriately. I tried this:

root@bt:~/sslsplit# LIBEVENT_BASE=/usr/lib/libevent.a
root@bt:~/sslsplit# make
GNUmakefile:175: **\* dependency 'libevent 2.x' not found; install it or point LIBEVENT_BASE to base path.  Stop.

any idea what I am doing wrong?

**Comment by kbutti** [comment]
FYI: `yum install libevent-devel.i686` made me happy.
