### ISSUE TITLE
Session master key logging

### ISSUE THREAD

**Issue by Neoptolemus** [droe/sslsplit#121]
Hello,

is it possible to log session master keys ? If yes then could you specify how to do that?

This could be really useful for users who need to capture traffic to *.pcap files. They could then import pcap files into wireshark and decrypt them with the SSLKEYLOGFILE. This way you can decrypt even sessions which use ECDHE or DHE as key exchange mechanism.

I think this shouldn't be very hard to implement, hence the sslsplit probably has the session master keys stored somewhere.

Thanks.

**Comment by johnwblue** [comment]
I know it is easier said than done, however based upon the tinkering that I have done with sslsplit, this feature request is the one feature that sslsplit is missing.  Using the SSLKEYLOGFILE is nice if all of the work is being done in a browser, but I want to route non-browser based traffic through sslsplit and port mirror the traffic to a wireshark box.  I have had some success forcing RSA but it sure would be nice to just let it flow however it wants DH and all.

Thank you for your hard work on this!

John

**Comment by droe** [comment]
References that might be helpful for implementation:
http://security.stackexchange.com/questions/80158/extract-pre-master-keys-from-an-openssl-application
https://wiki.wireshark.org/SSL#Complete_SSL_decryption_walk_through
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Key_Log_Format

**Comment by droe** [comment]
Implemented in 503e75cce1af758065fb59c457fc6f424007d785.
