### ISSUE TITLE
get duplicate traffic in pxy_bev_readcb

### ISSUE THREAD

**Issue by david-holonet** [droe/sslsplit#123]
When the network is not so good, I always get the same piece of traffic from bufferevent, is it retransmission traffic? But I guess maybe buffevent will drop the retransmission TCP traffic, right?

**Comment by droe** [comment]
Actual TCP segment retransmissions are sorted out by the kernel and never reach userland. So if you are seeing traffic duplicates, it means that either the client is actually sending duplicate requests on application level (like making multiple connections at the same time requesting the same thing), or that there is a bug in libevent or SSLsplit. If you are sure it is the latter, please do open a ticket (or re-open this one).
