### ISSUE TITLE
Is it possible to get BEV_EVENT_EOF before BEV_EVENT_CONNECTED ?

### ISSUE THREAD

**Issue by eunsoopark** [droe/sslsplit#124]
I am running sslsplit with my test network and got segmentation fault message sometime.

With segmentaion fault stack dump message and my debugging code, I found that befferevent get event BEV_EVENT_EOF before BEV_EVENT_CONNECTED.

I wonder whether this happen.

I add some codes to run my test network. Check please.

```patch
--- pxyconn.c.org   2016-03-16 14:02:05.280290836 +0900
+++ pxyconn.c   2016-03-16 14:09:15.853956399 +0900
@@ -1899,21 +1899,26 @@
    }

    if (events & BEV_EVENT_EOF) {
-       if (!other->closed) {
-           struct evbuffer *inbuf, *outbuf;
-           inbuf = bufferevent_get_input(bev);
-           outbuf = bufferevent_get_output(other->bev);
-           if (evbuffer_get_length(inbuf) > 0) {
-               evbuffer_add_buffer(outbuf, inbuf);
-           } else {
-               /* if the other end is still open and doesn't
-                * have data to send, close it, otherwise its
-                * writecb will close it after writing what's
-                * left in the output buffer. */
-               if (evbuffer_get_length(outbuf) == 0) {
-                   bufferevent_free_and_close_fd(
-                           other->bev, ctx);
-                   other->closed = 1;
+       if (!ctx->connected) {
+           log_dbg_printf("BEV_EVENT_EOF befor BEV_EVENT_CONNECTED");
+           evutil_closesocket(ctx->fd);
+           other->closed = 1;
+       } else if (!other->closed) {
+               struct evbuffer *inbuf, *outbuf;
+               inbuf = bufferevent_get_input(bev);
+               outbuf = bufferevent_get_output(other->bev);
+               if (evbuffer_get_length(inbuf) > 0) {
+                   evbuffer_add_buffer(outbuf, inbuf);
+               } else {
+                   /* if the other end is still open and doesn't
+                    * have data to send, close it, otherwise its
+                    * writecb will close it after writing what's
+                    * left in the output buffer. */
+                   if (evbuffer_get_length(outbuf) == 0) {
+                       bufferevent_free_and_close_fd(
+                               other->bev, ctx);
+                       other->closed = 1;
+                   }
                }
            }
        }
```

**Comment by droe** [comment]
Haven't tested your code yet, but if BEV_EVENT_EOF before BEV_EVENT_CONNECTED for the same connection really happens, I suspect that would be a bug in libevent, possibly only some versions or some backends.

**Comment by droe** [comment]
My bad, I misread your description. This is definitely a bug in sslsplit. We can get BEV_EVENT_EOF on the inbound connection while BEV_EVENT_CONNECTED on the outbound connection has not been received yet. I'll commit a fix asap. Again, thanks for the bug report including patch!

**Comment by eunsoopark** [comment]
I think we have some miss communication. Sorry for my poor english :-(

In my case, outbound connection(DST) got BEV_EVENT_EOF before BEV_EVENT_CONNECTED in same connection.

SRC BEV is made when DST BEV get BEV_EVENT_CONNECTED. SRC can't get bufferevent event before DST BEV get BEV_EVENT_CONNECTED.


I'm focusing on libevent and openssl. Need more analysis and test.

1. libevent got openssl error while connecting to server.

2. libevent change BEV_EVENT_ERROR to BEV_EVENT_EOF when get openssl error SSL_ERROR_ZERO_RETURN or SSL_ERROR_SYSCALL. (conn_closed()@bufferevent_openssl.c)

**Comment by droe** [comment]
D'oh, you are totally right, that was more of a thinking problem on my side than a language problem :-) The fix is correct, just the error message and the NEWS text is wrong. I'll fix it, sorry about that.
