### ISSUE TITLE
How do you know when a connection ended?

### ISSUE THREAD

**Issue by mattes** [droe/sslsplit#128]
I'm reading payload chunks from a named pipe. As of today this is what SSLsplit writes to the named pipe:

`2016-02-09 22:47:15 UTC [10.0.21.2]:58800 -> [91.189.88.152]:80 (163):`

Is there any way to tell, when not to expect any further payload chunks for a particular connection? Maybe SSLsplit could log something like this:

`2016-02-09 22:47:15 UTC [10.0.21.2]:58800 -> [91.189.88.152]:80 (EOF)`

**Comment by droe** [comment]
Currently, that's missing, and should be added. I was thinking about adding a new log format in order not to break existing parsers. Your proposal however is simple and I like it.

**Comment by tracycodes** [comment]
I like this format. This is a crucial feature for any real time log parsing.

**Comment by droe** [comment]
Implemented, testing welcome.

**Comment by mattes** [comment]
That's awesome! Thank you!
