### ISSUE TITLE
Log Format

### ISSUE THREAD

**Issue by ns25** [droe/sslsplit#135]
Hi Daniel, I noticed that entire request and some part of response (headers) are logged properly (ie. in readable format) in the logs but not the response content/body. For example, content-type of the response is html, text or javascript but the body part remains in non-readable format. Could you please let me know if there is a way to log the responses too as per the content-type?

**Comment by droe** [comment]
Can you post an example log illustrating the problem along with configuration details and the output of `sslsplit -V`?

**Comment by ns25** [comment]
Attached log files:
[20160425T215954Z-[192.168.111.129]%3A1047-[216.58.196.67]%3A443.txt](https://github.com/droe/sslsplit/files/235637/20160425T215954Z-.192.168.111.129.3A1047-.216.58.196.67.3A443.txt)
[20160425T215955Z-[192.168.111.129]%3A1049-[216.58.196.67]%3A443.txt](https://github.com/droe/sslsplit/files/235638/20160425T215955Z-.192.168.111.129.3A1049-.216.58.196.67.3A443.txt)
[20160425T215955Z-[192.168.111.129]%3A1050-[216.58.196.67]%3A443.txt](https://github.com/droe/sslsplit/files/235639/20160425T215955Z-.192.168.111.129.3A1050-.216.58.196.67.3A443.txt)


Output of "sslsplit -V": 
SSLsplit 0.4.11 (built 2015-06-16)
Copyright (c) 2009-2014, Daniel Roethlisberger <daniel@roe.ch>
http://www.roe.ch/SSLsplit
Build info: V:FILE
Features: -DHAVE_NETFILTER
NAT engines: netfilter* tproxy
netfilter: IP_TRANSPARENT SOL_IPV6 !IPV6_ORIGINAL_DST
Local process info support: no
compiled against OpenSSL 1.0.2c 12 Jun 2015 (1000203f)
rtlinked against OpenSSL 1.0.2d 9 Jul 2015 (1000204f)
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
Using SSL_MODE_RELEASE_BUFFERS
SSL/TLS protocol availability: ssl3 tls10 tls11 tls12
SSL/TLS algorithm availability: RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW                                                                                        _UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSIO                                                                                        N_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.0.21-stable
rtlinked against libevent 2.0.21-stable
1 CPU cores detected

I used the following commands within ubuntu:
1) sudo openssl genrsa -out /home/my/myca.key 2048
2) sudo openssl req -new -x509 -days 365 -key /home/my/myca.key -out /home/my/myca.crt 
3) sudo ./sslsplit -D -l con.log -j /tmp/sslsplit/ -S logs/ -k /home/my/mykey.key -c /home/my/myca.crt ssl 0.0.0.0 8443 tcp 0.0.0.0 8080

**Comment by droe** [comment]
Try using "https 0.0.0.0 8443" instead of "ssl 0.0.0.0 8443", does it help?

**Comment by ns25** [comment]
Thanks a ton Daniel, tool worked well with https. Did not realize that I was doing everything to 'debug' this but to try https. Thanks again for your help :)

**Comment by droe** [comment]
The trick is that in plain SSL mode (`ssl`), sslstrip does not parse HTTP and thus does not remove "harmful" headers like `Alternate-Protocols:` or everything HSTS and HPKP related. All the hacks that are related to the HTTP protocol are only active in `http` and `https` proxyspecs. `ssl` is meant for non-HTTP SSL traffic.
