### ISSUE TITLE
HSTS related behavior

### ISSUE THREAD

**Issue by TalaatHarb** [droe/sslsplit#136]
In the overview it said in this exact words ",HSTS to allow the user to accept untrusted certificates" but this isn't currently the case as Firefox,Chrome and Edge do block communications with untrusted certificates with no exception now. it would be preferable to be able to at least allow the user to accept the certificate.

**Comment by droe** [comment]
26edfe4 changes the description to be more precise and accurate. If the browsers implement protections against MitM attacks through out-of-band means, there is little a tool like `sslsplit` can do about it. If you have any specific proposal on what evasion method should be added, please open a new issue with a description of the method. Thanks for pointing out the inaccuracy in the current descriptions.
