### ISSUE TITLE
AES-NI feature

### ISSUE THREAD

**Issue by armman475** [droe/sslsplit#144]
sslsplit is a great tool. It's very useful and amazing.
I test sslsplit performance in new platform（support AES-NI） and old platform(not support AES-NI), but
the test results not very different. It should be significantly improve performance. 
I don't know why.Please help check it. 
thanks.

openssl speed -elapsed -evp aes-128-cbc
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-128-cbc     489944.58k   525437.63k   536901.01k   537600.00k   538334.55k

OPENSSL_ia32cap="~0x200000200000000" openssl speed -elapsed -evp aes-128-cbc
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-128-cbc     217305.11k   245332.71k   251330.56k   254743.89k   254708.39k

openssl speed -elapsed  aes-128-cbc
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-128 cbc      95535.38k   104996.27k   107651.51k   108085.93k   108503.04k

**Comment by droe** [comment]
Performance of sslsplit under a normal workload is dominated by the signing of forged certificates and performing the SSL/TLS handshake, setting up the master secret. The symmetrical encryption/decryption makes only for a small part of the computational burden.

That being said, how did you test sslsplit performance, what results did you expect, what results did you get?

**Comment by armman475** [comment]
Thank you for your reply.
I test sslsplit through Ixia. The test result is like this:
Protocol:TLS1.0   cipher suites:AES128-SHA   900conncection/second   30Mbps Throughput 

But the BlueCoat Visibility appliance, SV3800B-20 performance data:
SSL Inspection Throughput----9Gbps
Concurrent SSL Flow States----800，000
New Full Handshake SSL Sessions----30，000per second

The gap is so big.How it is implemented?

**Comment by droe** [comment]
Firstly, never compare on-paper specs of solution A with real-world specs of solution B :)
Secondly, and more seriously, you should test using comparable hardware. According to their docs, BlueCoat has "flow processing hardware and cryptographic acceleration hardware". The latter does not mean only AES-NI, that means accelerated RSA. And yes, that's easily factors of a difference, especially with larger key sizes. Not sure how much of an impact flow processing hardware makes, but it would certainly help getting into higher numbers of connections.

I am not sure what you need help with.

**Comment by armman475** [comment]
Thank you for your patience reply.
I just want to improve sslsplit performance. I used oprofile tools, and found sslsplit function hotspot.
 1108     39.8275  ssl_thr_locking_cb
 225       8.0877  kh_put_dynbufmap_t
 175       6.2904  kh_get_dynbufmap_t
 136       4.8886  pxy_bev_eventcb
 92        3.3070  ssl_thr_id_cb
 78        2.8037  kh_put_dynbufmap_t
 52        1.8692  pxy_fd_readcb
 50        1.7973  kh_dynbuf_hash_func
 49        1.7613  pxy_bev_readcb
 41        1.4738  pxy_ssl_shutdown_cb
 33        1.1862  pxy_bufferevent_setup
 32        1.1503  cachedsess_mkkey
 30        1.0784  ssl_tls_clienthello_parse
 29        1.0424  pxy_srcssl_create
I think sslsplit bottleneck is mutex. Is there any good solution?

**Comment by droe** [comment]
Your list only includes functions in sslsplit, but omits functions in libevent, libssl and libcrypto. The "bottleneck" a.k.a. main processing burden is within libcrypto. Because libssl calls the ssl_thr_locking_cb, that function appears high in the sslsplit code, but does not necessarily rank high if you include library code in your profiling too.

Closing this issue. While it is an interesting discussion, it does not solve any problems related to sslsplit.
