### ISSUE TITLE
Openssl asynchronous support

### ISSUE THREAD

**Issue by armman475** [droe/sslsplit#150]
Openssl 1.1.x provides asynchronous support. 
Now there are two problems：
1 There are some errors when the program is compiled；
2 How to use asynchronous mode in sslsplit?
I look forward to your reply.Thank you.

**Comment by droe** [comment]
1) Check open issues and if none match, open a new one with the exact compile failure.
2) What problem are you trying to solve? SSLsplit already uses OpenSSL in an asynchronious way, through libevent2_openssl. There might be benefits of migrating both libevent2_openssl and SSLsplit to the new async OpenSSL API, but I don't expect any user-visible changes that would result in. Closing this issue.
