### ISSUE TITLE
Not all HTTP(S) headers logged?

### ISSUE THREAD

**Issue by tmjvonboss** [droe/sslsplit#155]
GET http://url.com/url HTTP/1.1
User-Agent: SomeApp
Accept-Encoding: identity, gzip
Host: url.com
Connection: Keep-Alive

I used sslsplit to intercept connections from my adroid phone, on my phone I have installed a trust certificate for sslsplit so I can intercept that traffic
I noticed that not all of the headers are in the logged requests, is there an option to log that too? Or perhaps I did something wrong?

**Comment by droe** [comment]
All headers should be logged. If you are missing some headers, please provide specific information, including the relevant logs and the output of `sslsplit -V`.

**Comment by droe** [comment]
Timeout.
