### ISSUE TITLE
Sslsplit Trusted certificates: question

### ISSUE THREAD

**Issue by gauravcmu** [droe/sslsplit#158]
Hello, 

This is more of a question to understand the behavior and how sslsplit handles it than an issue. Hope it is ok to ask here. 

Client / user <---------> sslsplit <----------> server 

My question is that how does sslsplit handle server certificate validation, meaning when the server provides sslsplit with a certificate, does it look at the certificate to do validation or does it ignore it. If it does this validation of the server certificate, how can I add certificate for a server which presents a certificate not in the trusted list. What is the behavior in case if there is no trusted certificate authority in the certificate chain? Will sslsplit bypass the connection or tear it down. 

Please let me know if I should add some more details to my question or ask this elsewhere. 

Thanks, 
Gaurav

**Comment by droe** [comment]
SSLsplit does not validate the server certificate. Feel free to submit a pull request implementing optional certificate validation.

I marked this as a documentation issue since the manual page does not seem to mention this anywhere.

**Comment by gauravcmu** [comment]
Thanks for confirming.
