### ISSUE TITLE
Disable sending orig. Cert to Client

### ISSUE THREAD

**Issue by RentonXD** [droe/sslsplit#160]
Hello,

I'm not sure if it's a bug or I'm using it wrong. 
I've set up a RaspberryPi 3 as Proxy with SslSplit to sniff the traffic of my iPad.
It seems to work well, but in one case it doesn't.
The log tells me this:

SNI peek: [mcoc-1120-hrkan.sparxcdn.net] [complete]
Attempt reuse dst SSL session
Connecting to [54.230.45.128]:443
===> Original server certificate:
Subject DN: /OU=Domain Control Validated/CN=*.sparxcdn.net
Common Names: *.sparxcdn.net/*.sparxcdn.net/sparxcdn.net
Fingerprint: 5C:F9:62:94:2F:99:B0:9C:D7:9B11:9A:3C:75:1C:62:02:21:C5:F9
Certificate cache: HIT
===> Forged server certificate:
Subject DN: /OU=Domain Control Validated/CN=*.sparxcdn.net
Common Names: *.sparxcdn.net/*.sparxcdn.net/sparxcdn.net
Fingerprint: 9D:9D:A3:98:FF:E5:77:EE:3C:F33B:A5:5A:6E:22:F4:78:EE:6E:B5
SSL connected to [54.230.45.128]:443 TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256
Received privsep req type 01 sz 81 on srvsock 10
SSL session cache: HIT
Certificate cache: KEEP (SNI match or target mode)
ssl 192.160.1.90 49749 54.230.45.128 443 sni:mcoc-1120-hrkan.sparxcdn.net names:*.sparxcdn.net/*.sparxcdn.net/sparxcdn.net sproto:TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384 dproto:TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256 origcrt:5CF962942F99B09CD79B119A3C751C620221C5F9 usedcrt:9D9DA398FFE577EE3CF33BA55A6E22F478EE6EB5
SSL connected from [192.160.1.90]:49749 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384
Unclean SSL shutdown.
SSL disconnected to [54.230.45.128]:443
SSL disconnected from [192.160.1.90]:49749

So I've tried to watch this in Wireshark. There I can see that the original Server gives me 4 possible certs. Nothing special so far I guess. But the proxy offers one of these and additionally my own cert to the client. I don't know why it does this and if it is common. But I've also decompiled the App and there it always chooses the first valid cert (which is the original one).

So how can I avoid sending the original Cert (additionally) to the Client.
Or better: What I'm doing wrong?

**Comment by droe** [comment]
Please provide the PCAP showing this behaviour and the output of `sslsplit -V`

**Comment by RentonXD** [comment]
Hello,

thanks for your reply.

The SslSplit Info output:

SSLsplit 0.5.0 (built 2017-01-20)
Copyright (c) 2009-2016, Daniel Roethlisberger <daniel@roe.ch>
http://www.roe.ch/SSLsplit
Build info: V:FILE
Features: -DHAVE_NETFILTER
NAT engines: netfilter* tproxy
netfilter: IP_TRANSPARENT SOL_IPV6 !IPV6_ORIGINAL_DST
Local process info support: no
compiled against OpenSSL 1.0.1t  3 May 2016 (1000114f)
rtlinked against OpenSSL 1.0.1t  3 May 2016 (1000114f)
OpenSSL has support for TLS extensions
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
Using SSL_MODE_RELEASE_BUFFERS
SSL/TLS protocol availability: ssl3 tls10 tls11 tls12
SSL/TLS algorithm availability: RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.0.21-stable
rtlinked against libevent 2.0.21-stable
4 CPU cores detected


And attached the pcap. 
Server: 54.192.202.121
Client: 192.160.1.90
Proxy: 192.168.178.140

[SslSplitEncryptedAlertForGithub (54.192.202.121).pcapng.zip](https://github.com/droe/sslsplit/files/742408/SslSplitEncryptedAlertForGithub.54.192.202.121.pcapng.zip)

**Comment by droe** [comment]
Ah okay now I understand what you meant. The original server offers a certificate chain of 4 certificates. SSLsplit only offers a chain of two certificates: The CA certificate you use for SSLsplit and the forged version of the server certificate, that looks similar to the original server certificate but has a different fingerprint and less extensions.

It is true that sending the CA certificate along is not needed, but it should not hurt either.

Why is this a problem for you?

**Comment by RentonXD** [comment]
I thought this would be the reason for the encrypted alert you can see in the pcap. So my problem is that the ssl connection doesn't work. The client is aborting it every time. Do you have any hint what's wrong there or what I can do to make it work?

**Comment by droe** [comment]
A lot of things can be the reason for the encrypted alert you can see, including a regular secure shutdown of the connection.

I will close this issue; feel free to reopen a new issue if you can narrow down the problem more and it turns out there is something we can fix in SSLsplit.
