### ISSUE TITLE
WebSockets

### ISSUE THREAD

**Issue by hashsim** [droe/sslsplit#161]
Hello, 

Does sslsplit support websockets? 

If a browser using HTTPS, initiates websocket connection to the server, would sslsplit allow it or drop it. It seems to be dropping it. Would it be possible to detect websocket connections and split it or bypass it completely. 

Thanks,
Gaurav

**Comment by danieljimenez** [comment]
Plus one.

**Comment by droe** [comment]
- [ ] Refactor the proxy core; split out protocol handling
- [ ] Implement web sockets protocol
- [ ] Implement upgrading HTTP/1.x to websockets
- [ ] Extend logging to websockets
