### ISSUE TITLE
TLS 1.3

### ISSUE THREAD

**Issue by hashsim** [droe/sslsplit#162]
Hello, 

thank you for this great tool! 

This is more of a question, not an issue. 

It looks like TLS1.3 is not supported with sslsplit currently. Is there a plan to support TLS 1.3?

Thank you.

**Comment by droe** [comment]
- [ ] Achieve minimal support for TLS 1.3 by supporting OpenSSL 1.1.1
- [ ] Adapt all SSL/TLS configuration options (like -r, -R, -s, -g, -G etc) to fully work with new TLS 1.3 concepts, add TLS 1.3 examples to documentation where there are differences vs TLS 1.2 (such as cipher suites)
- [ ] Adjust our own ClientHello parser to deal with TLS 1.3, including encrypted SNI (w/any TLS version)
- [ ] Ensure encrypted SNI is handled as gracefully as possible in the maximum number of situations; unbreak as many use cases that depend on SNI being available as possible

Useful reference: https://www.openssl.org/blog/blog/2017/05/04/tlsv1.3/
