### ISSUE TITLE
About DPDK

### ISSUE THREAD

**Issue by armman475** [droe/sslsplit#163]
Hi droe.
I want to know the effect of sslsplit on the dpdk(Data Plane Development Kit) platform. For example，performance improvement.
Have any ideas and suggestions?

**Comment by iBreaker** [comment]
猜你能看懂中文

目前只能通过dpdk写入内核，通过内核协议栈把数据给sslsplit 的办法解决吧？
或者用mTcp？

**Comment by armman475** [comment]
Thanks iBreaker.
Is there a proxy solution on the DPDK platform?

**Comment by mmanoj** [comment]
@armman475 

This is good feature to have it, I'm also looking the same feature. Thanks for bring it up. Hope developers can comment on this, or some one can start to modify the code.

**Comment by droe** [comment]
Building sslsplit on top of DPDK would essentially be a total rewrite. This is not planned. Feel free to fork the project and rebase it on DPDK with a custom TCP stack.
