### ISSUE TITLE
question of usage about -g argument and parse DH or ECDH

### ISSUE THREAD

**Issue by david-holonet** [droe/sslsplit#164]
I'm not familiar with the usage of DH and ECDH, and I do not know how to use "-g" and "-G" arguments. Can you give me some example or advice?
I do not set any value to "-g" or "-G" argument.
Now I meet an issue when connecting to Evernote from Mac application. SSL proxy always returns "ssl3_read_bytes:sslv3 alert certificate unknown", which uses Elliptic curves in Client-Hello message. I want to know whether my usage of SSLSPLIT is right.
Expect your answer. thanks!

**Comment by droe** [comment]
In (very rare) cases where a client or server does not work with certain curves or DH params, -g and -G are useful to achieve compat. Generally however you will not need to use them. The certificate unknown alert message indicates that either the client did not like the server certificate (if you get the alert from the client), or that the server did not like the client certificate (if you get it from the server).
