### ISSUE TITLE
peeking did not yield client hello?

### ISSUE THREAD

**Issue by yogi-dmt** [droe/sslsplit#172]
I did a wireshark capture and see that some clienthellos are being sent. I also do see that traffic is running through sslsplit. I've tried a few different ways already (settings the vm as the def gateway, routing 443 traffic to the vm port 8443, and the windows proxy settings). For each case traffic does indeed seem to be reaching sslsplit but for some reason it cannot see any of the clienthellos?

**Comment by droe** [comment]
Possibly linked to #185 and fixed in latest `develop`.
