### ISSUE TITLE
SSLv2ClientHello not supported

### ISSUE THREAD

**Issue by stef** [droe/sslsplit#185]
i'm getting these debug messages:
```
ClientHello parser: parsing buffer of sz 54
ClientHello parser: candidate at offset 0
ClientHello parser: byte 0: 80
ClientHello parser: ===> No match: rv 1, *clienthello NULL
Peeking did not yield a (truncated) ClientHello message, aborting connection
```
it seems i'm hitting this unhandled case: https://github.com/droe/sslsplit/blob/7bc9f8784280ccfd8304dec17adef5379238fb10/ssl.c#L1992

## Output of `sslsplit -V`
```
SSLsplit 0.5.1 (built 2018-02-04)
Copyright (c) 2009-2018, Daniel Roethlisberger <daniel@roe.ch>
http://www.roe.ch/SSLsplit
Build info: V:FILE
Features: -DDEBUG_CLIENTHELLO_PARSER -DHAVE_NETFILTER -DWITH_SSLV2
NAT engines: netfilter* tproxy
netfilter: IP_TRANSPARENT IP6T_SO_ORIGINAL_DST
Local process info support: no
compiled against OpenSSL 1.0.2n  7 Dec 2017 (100020ef)
rtlinked against OpenSSL 1.0.2n  7 Dec 2017 (100020ef)
OpenSSL has support for TLS extensions
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
Using SSL_MODE_RELEASE_BUFFERS
SSL/TLS protocol availability: ssl2 ssl3 tls10 tls11 tls12
SSL/TLS algorithm availability: SHA0 RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_
OP_TLS_ROLLBACK_BUG
compiled against libevent 2.1.8-stable
rtlinked against libevent 2.1.8-stable
4 CPU cores detected
```
## Exact command line arguments used to run `sslsplit`
```
sudo ./sslsplit -e tproxy -D -L sniff.log -c ./cert.pem https 10.17.17.1 10443
```

## Relevant part of debug mode (-D) output, if applicable
see above

## NAT redirection rules you are using, if applicable
seems irrelevant in this case.

## The payload looks like this:

https://www.ctrlc.hu/~stef/sslv2.png

**Comment by droe** [comment]
The fact that it affects setups other than `autossl` makes this a bug; that the ClientHello peeking does not support SSLv2 yet is a missing feature. In any case something that should be remedied.

**Comment by droe** [comment]
I believe this is fixed in latest `develop` - please let me know if it works for you. Thanks for the report.

**Comment by stef** [comment]
i can confirm! great job! quick and professional! thanks a lot! <3
s

**Comment by StevePham88** [comment]
Hi Droe,
Im getting the same issue with Ssl2. I have already used the latest sslsplit v0.5.2 but sslv2 not supported. Please help
![image](https://user-images.githubusercontent.com/19483861/41580541-70162022-73c5-11e8-8650-2b03fc4dad73.png)

**Comment by droe** [comment]
SSLv2 is supported in 0.5.2 if you build it against a version of OpenSSL that still supports SSLv2.

**Comment by StevePham88** [comment]
Im using openssl version 1.0.1, do i need to upgrade the openssl? Thanks a lot

**Comment by droe** [comment]
You also need to add `-DWITH_SSLV2` to `FEATURES`, see the `GNUmakefile` for details.

**Comment by droe** [comment]
I'm locking this issue since it is not about general SSLv2 support.
