### ISSUE TITLE
How logreader.py files read and display logs of SSLsplit?

### ISSUE THREAD

**Issue by pleoeter** [droe/sslsplit#190]
Please supply the following with bug reports to allow for diagnostics:

-   Output of `sslsplit -V`
-   Output of `uname -a`
-   Exact command line arguments used to run `sslsplit`
-   Relevant part of debug mode (-D) output, if applicable
-   NAT redirection rules you are using, if applicable
-   List of failing unit tests in `make test` output
-   Other relevant data such as PCAPs, logs, screenshots etc

For build problems, please supply:

-   Output of `uname -a`
-   Full output of failed `make` including the header
-   Version and origin of OpenSSL used
-   Version and origin of libevent used

**Comment by droe** [comment]
It’s a small library, not a utility. See the `__name__ == “__main__”` code block or `log2pcap.py` for example use.
