### ISSUE TITLE
I cannot see username in the logdir? 

### ISSUE THREAD

**Issue by pleoeter** [droe/sslsplit#191]
I want to see the username and password of the victim, in Logdir no such info i can trace, sslplit is working fine 

-   Output of `sslsplit -V`
SSLsplit 0.5.2-3-g04b1214-dirty (built 2018-04-30)
Copyright (c) 2009-2018, Daniel Roethlisberger <daniel@roe.ch>
https://www.roe.ch/SSLsplit
Build info: V:GIT
Features: -DHAVE_NETFILTER
NAT engines: netfilter* tproxy
netfilter: IP_TRANSPARENT IP6T_SO_ORIGINAL_DST
Local process info support: no
compiled against OpenSSL 1.0.2g  1 Mar 2016 (1000207f)
rtlinked against OpenSSL 1.0.2g  1 Mar 2016 (1000207f)
OpenSSL has support for TLS extensions
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
Using SSL_MODE_RELEASE_BUFFERS
SSL/TLS protocol availability: ssl3 tls10 tls11 tls12 
SSL/TLS algorithm availability: SHA0 RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.0.21-stable
rtlinked against libevent 2.0.21-stable
2 CPU cores detected

-   Output of `uname -a`
Linux ubuntu 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
-   Exact command line arguments used to run `sslsplit`
sudo ./sslsplit -D -l connections.log -j /tmp/sslsplit/ -S /tmp/logdir/ -k ca.key -c ca.crt ssl 0.0.0.0 8443 tcp 0.0.0.0 8080

In logdir i only see the connection information and cookies as

20180430T090531Z-192.168.20.3,20321984-470024384,443.log

**Comment by droe** [comment]
Unmodified sslsplit logs whatever is transmitted between client and server to the log file. If you have the cookies there, then so should you have the POST bodies containing login credentials of typical web applications.

The output of `sslsplit -V` indicates that you have made modifications to the source code. Also, the log filename was not generated by the default implementation of `-S` (but perhaps you've just edited that). In either case, please provide a complete test case using an unmodified version of sslsplit for me to reproduce the issue.

**Comment by pleoeter** [comment]
Yes i modified it, now i can see it again , Thankyou @droe Droe
