### ISSUE TITLE
Support AWS CloudHSM as an alternative OpenSSL engine

### ISSUE THREAD

**Issue by reedloden** [droe/sslsplit#204]
Instead of requiring that the private key be local to the instance, would be good to support alternative engines, specifically at least AWS CloudHSM (the OpenSSL `cloudhsm` engine).

https://docs.aws.amazon.com/cloudhsm/latest/userguide/openssl-library-install.html#install-openssl-library and https://docs.aws.amazon.com/cloudhsm/latest/userguide/ssl-offload-import-or-generate-private-key-and-certificate.html have more details.

Everything else should stay the same, so should be easy to integrate. Just need to support setting the engine. On the command line, this is done via `-engine cloudhsm`. In code, generally something like this (just dummy code as an example):

```
ENGINE *e;
 
if (!(e = ENGINE_by_id("cloudhsm")))
    fprintf(stderr, "Error finding specified ENGINE\n");
else if (!ENGINE_set_default(e, ENGINE_METHOD_ALL))
    fprintf(stderr, "Error using ENGINE\n");
else
    fprintf(stderr, "Engine successfully enabled\n");
```

**Comment by droe** [comment]
Is there an easy way to test engine support without AWS account or actual HSM hardware?

**Comment by reedloden** [comment]
Not sure there's a way to test CloudHSM without an instance specifically (I doubt it), but it should be good enough to support different dynamic engines, and CloudHSM is just another one of those.

https://github.com/openssl/openssl/blob/master/README.ENGINE
https://www.openssl.org/docs/man1.1.0/apps/engine.html
https://wiki.openssl.org/index.php/Library_Initialization#Engines

Based on that last one, it may be possible to just call `ENGINE_load_builtin_engines` or `OPENSSL_config` and defer engine selection to `openssl.cnf`, perhaps? Not sure.

**Comment by droe** [comment]
The initial implementation in the `engine` branch seems to work in that it is able to load a dummy engine by path, on at least macOS and Linux.

@reedloden are you able to test drive the `engine` branch on AWS with `-x cloudhsm`?

**Comment by reedloden** [comment]
Just tested. Works!

Took me a while to figure out all the bits and pieces (CloudHSM setup isn't for the faint of heart), but was able to get it working just fine.

```
ubuntu@ip-172-31-18-38:~/sslsplit$ export n3fips_password=example_user:examplePassword
ubuntu@ip-172-31-18-38:~/sslsplit$ ./sslsplit -D -x cloudhsm -k customerCA.key -c customerCA.crt -P  https 127.0.0.1 8443  https ::1 8443
OpenSSLEngine: cloudhsm
Enter PEM pass phrase:
CAKey: customerCA.key
CACert: customerCA.crt
	SDK Version: 2.03
SSLsplit 0.5.3-56-g449c057 (built 2018-08-22)
Copyright (c) 2009-2018, Daniel Roethlisberger <daniel@roe.ch>
https://www.roe.ch/SSLsplit
Build info: V:GIT
Features: -DHAVE_NETFILTER
NAT engines: netfilter* tproxy
netfilter: IP_TRANSPARENT IP6T_SO_ORIGINAL_DST
Local process info support: no
compiled against OpenSSL 1.0.2g  1 Mar 2016 (1000207f)
rtlinked against OpenSSL 1.0.2g  1 Mar 2016 (1000207f)
OpenSSL has support for TLS extensions
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
Using SSL_MODE_RELEASE_BUFFERS
SSL/TLS protocol availability: ssl3 tls10 tls11 tls12
SSL/TLS algorithm availability: SHA0 RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.0.21-stable
rtlinked against libevent 2.0.21-stable
1 CPU cores detected
Generated RSA key for leaf certs.
SSL/TLS protocol: negotiate
proxyspecs:
- [::1]:8443 ssl|http netfilter
- [127.0.0.1]:8443 ssl|http netfilter
Loaded OpenSSL engine cloudhsm
Loaded CA: '/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd'
Created self-pipe [r=4,w=5]
Created chld-pipe [r=6,w=7]
Created socketpair 0 [p=8,c=9]
Created socketpair 1 [p=10,c=11]
Created socketpair 2 [p=12,c=13]
Using libevent backend 'epoll'
Event base supports: edge yes, O(1) yes, anyfd no
Received privsep req type 03 sz 9 on srvsock 8
Received privsep req type 03 sz 9 on srvsock 8
Received privsep req type 00 sz 1 on srvsock 8
Dropped privs to user - group - chroot -
Received privsep req type 00 sz 1 on srvsock 10
Received privsep req type 00 sz 1 on srvsock 12
Inserted events:
  0x1b9b1a0 [fd 7] Read Persist
  0x1b9b6c0 [fd 8] Read Persist
  0x1b9b780 [fd 10] Read Persist
  0x1b9afd8 [fd 6] Read Persist
  0x1b9ad00 [fd 15] Signal Persist
  0x1b9ba50 [fd 3] Signal Persist
  0x1b9bb80 [fd 1] Signal Persist
  0x1b9bcb0 [fd 2] Signal Persist
  0x1b9be00 [fd 13] Signal Persist
  0x1b9bf70 [fd 10] Signal Persist
Initialized 2 connection handling threads
Started 2 connection handling threads
Starting main event loop.
```

**Comment by droe** [comment]
Branch slated for merging into `develop` in #206, closing this issue. Thanks for the feature request and testing w/CloudHSM.
