### ISSUE TITLE
SSL disconnect: ettercap, pf & sslsplit

### ISSUE THREAD

**Issue by aboulfad** [droe/sslsplit#212]
Hello,

I've been trying to get sslsplit to play along ettercap and pf for the following objective: capture an TLS session between LG TV+ remote running on my iPhone and my LG smartTV. The iOS app after discovering the LGTV using SSDP, initiates a TLS session on port 3001. Both Mac and LgTV are wired to the router.

For some reason, and as seen in the sslsplit.log file (terminal stdout):[sslsplit.log](https://github.com/droe/sslsplit/files/2342041/sslsplit.log)
 sslsplit disconnects, which is also seen in the ettercap pcap captured file.
[ip6_ettercap_pf_sslsplit_FAIL.pcap.zip](https://github.com/droe/sslsplit/files/2342039/ip6_ettercap_pf_sslsplit_FAIL.pcap.zip)

A sucessful connection between iPhone and TV and using ettercap (no sslsplit or pf) can be found 
here: [ip6_ettercapConn_Vol.pcapng.zip](https://github.com/droe/sslsplit/files/2342052/ip6_ettercapConn_Vol.pcapng.zip)

The pem file used is the output of the [GNUMakefile](https://github.com/droe/sslsplit/blob/develop/extra/pki/GNUmakefile) in extras/pki dir and is added to the iphone trust store. Unsure if there is some conflict between ettercap forwarding all traffic in Unified mode, as well as sslsplit when it intercepts the TLS connection.

Any ideas are appreciated :-)
![lgtv](https://user-images.githubusercontent.com/16640625/44941821-66a90f80-ad73-11e8-9884-cc7e6e4b1e28.png)

-   Output of `sslsplit -V`
[sslsplitVer.txt](https://github.com/droe/sslsplit/files/2342011/sslsplitVer.txt)

-   Output of `uname -a`: MacOS HighSiera 10.13.6
-   Exact command line arguments used to run `sslsplit`
`sudo sslsplit -D -l connections.log -M sslkey.log -S logdir/ -c ~/.keys/rsaMBA.pem ssl 0.0.0.0 8443 
`
-   NAT redirection rules you are using, if applicable:
`rdr pass log (all) inet proto tcp from any to any port 3001 -> localhost port 8443 
`
-   Ettercap cmd:
`sudo ettercap -w temp.pcap -S -i en5 -Tq -M arp /192.168.10.101/ /192.168.10.102/
`

**Comment by droe** [comment]
Looking at the pcap and analyzing SSLsplit's inbound connection, TCP flow 1 (wireshark filter "tcp.stream eq 1"), I see that the original TCP SYN gets sent to both your Mac and later to your TV. If I am reading this correctly, your phone's TCP connection then gets torn down because two connections cannot be differentiated based on the 5-tuple (proto, srcip, srcport, dstip, dstport) and sequence numbers start to get out of sync at some point.

The fact that your TV receives and replies to this connection from your phone while the Mac also handles the same TCP connection would indicate your ettercap setup is not working as intended.

Also: Is that NAT redirection rule the only rule you have configured? That would also redirect SSLsplit's outbound connection back to itself, so I suspect this rule is not effective as shown, or you'd get different results.

From SSLsplit it looks like the TCP connection got closed regularly. This part of debug logging should be improved.

**Comment by droe** [comment]
If you can get me a debug log of that very same failed connection with `DEBUG_PROXY` defined (see GNUmakefile), that would be fab.

**Comment by aboulfad** [comment]
Bonjour/Guten Morgen :-)

Thank you for the reply. Indeed, you have confirmed my suspicions about my ill informed usage of ettercap and pf rules. I will switch back to using the simpler *arpspoof* and figure how to route packets on macos.

I have re-compiled sslsplit with **DEBUG_PROXY**, though unsure what additional debug logs if any were generated. The stdout shows `Features: -DDEBUG_PROXY -DHAVE_DARWIN_LIBPROC -DHAVE_PF`

Here's the stdout debug info which looks similar to before, -l/-L connection logs are empty as ssl session is "pre-maturely" disconnected.
<details>
  <summary>sslsplit STDOUT</summary> 
```
./sslsplit.sh
ContentLog: sslsplit.log
ConnectLog: connections.log
MasterKeyLog: sslkey.log
ContentLogDir: /Users/kylie/src/logdir
CACert: /Users/kylie/.keys/rsaMBA.pem
SSLsplit 0.5.3-66-gcd8c1e2-dirty (built 2018-09-02)
Copyright (c) 2009-2018, Daniel Roethlisberger <daniel@roe.ch>
https://www.roe.ch/SSLsplit
Build info: OSX:10.13.6 XNU:4570.41.2:fallback:4570.71.2 V:GIT
Features: -DDEBUG_PROXY -DHAVE_DARWIN_LIBPROC -DHAVE_PF
NAT engines: pf*
Local process info support: yes (Darwin libproc)
compiled against OpenSSL 1.0.2p  14 Aug 2018 (1000210f)
rtlinked against OpenSSL 1.0.2p  14 Aug 2018 (1000210f)
OpenSSL has support for TLS extensions
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
OpenSSL has engine support
Using SSL_MODE_RELEASE_BUFFERS
SSL/TLS protocol availability: ssl3 tls10 tls11 tls12 
SSL/TLS algorithm availability: SHA0 RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.1.8-stable
rtlinked against libevent 2.1.8-stable
4 CPU cores detected
Generated RSA key for leaf certs.
SSL/TLS protocol: negotiate
proxyspecs:
- [0.0.0.0]:8443 ssl pf
Loaded CA: '/C=CH/O=SSLsplit Root CA/CN=SSLsplit Root CA MBA'
NAT engine preinit 'pf'
Created self-pipe [r=7,w=8]
Created chld-pipe [r=9,w=10]
Created socketpair 0 [p=11,c=12]
Created socketpair 1 [p=13,c=14]
Created socketpair 2 [p=15,c=16]
NAT engine fini 'pf'
Using libevent backend 'kqueue'
Event base supports: edge yes, O(1) yes, anyfd yes
Received privsep req type 03 sz 9 on srvsock 11
Dropped privs to user - group - chroot -
Received privsep req type 00 sz 1 on srvsock 11
NAT engine init 'pf'
Inserted events:
  0x7fe965513298 [fd  8] Read Persist
  0x7fe965513920 [sig 1] Signal Persist
  0x7fe9655139a0 [sig 2] Signal Persist
  0x7fe9655138a0 [sig 3] Signal Persist
  0x7fe965513a40 [sig 13] Signal Persist
  0x7fe965512420 [sig 15] Signal Persist
  0x7fe965513ae0 [sig 30] Signal Persist
  0x7fe965513820 [fd  -1] Persist Timeout=1535883703.686829
Active events:
Initialized 8 connection handling threads
Received privsep req type 00 sz 1 on srvsock 15
Started 8 connection handling threads
Starting main event loop.


0x7fe9654096f0             pxy_conn_ctx_new
SNI peek: [192.168.10.101] [complete]
            0x7fe965603bb0 pxy_bufferevent_setup
Connecting to [192.168.10.101]:3001
0x7fe9654096f0 0x7fe965603bb0 eventcb dst connected
===> Original server certificate:
Subject DN: /C=US/ST=New Jersey/O=LG Electronics U.S.A, Inc./CN=LG_TV_e3082c225a18630
Common Names: LG_TV_e3082c225a18630
Fingerprint: 19:E4:A5:3E:E7:B9:1F:08:EB:B707:EA:42:ED:05:47:23:F6:85:29
Certificate cache: MISS
===> Forged server certificate:
Subject DN: /C=US/ST=New Jersey/O=LG Electronics U.S.A, Inc./CN=LG_TV_e3082c225a18630
Common Names: LG_TV_e3082c225a18630
Fingerprint: 9B:9F:C9:04:CE:D4:22:EC:B6:09CB:E4:88:F4:CC:BF:0B:A9:F3:0D
            0x7fe96551c2e0 pxy_bufferevent_setup
SSL connected to [192.168.10.101]:3001 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384
CLIENT_RANDOM A21037FA4C162245E919EDE5937BF7EFEA479E2FD3C4AEAE24836A210119A543 9A13515E7DA60EB1BD118939CA8A899518A51A59BC4D2EC942259CD506229C10565B18D8796D042B2BAAA9C8F90A8C8B
Received privsep req type 01 sz 86 on srvsock 13
Certificate cache: UPDATE (SNI mismatch)
===> Updated forged server certificate:
Subject DN: /C=US/ST=New Jersey/O=LG Electronics U.S.A, Inc./CN=LG_TV_e3082c225a18630
Common Names: LG_TV_e3082c225a18630/192.168.10.101
Fingerprint: 9E:D1:F3:4F:4D:E1:AE:CE:F8:5FC7:32:45:9B:98:B4:19:D9:E6:A4
0x7fe9654096f0 0x7fe96551c2e0 eventcb src eof
evbuffer size at EOF: i:0 o:0 i:0 o:0
            0x7fe965603bb0 free_and_close_fd
SSL disconnected to [192.168.10.101]:3001
SSL disconnected from [192.168.10.102]:49486
            0x7fe96551c2e0 free_and_close_fd
SSL_free() in state 00002190 = SSL_ST_ACCEPT|0190 = UNKWN  (unknown state) [accept socket]
0x7fe9654096f0             pxy_conn_ctx_free
SSL_free() in state 00000003 = 0003 = SSLOK  (SSL negotiation finished successfully) [connect socket]

Garbage collecting caches started.
Garbage collecting caches done.
^CReceived signal 2
Main event loop stopped.
NAT engine fini 'pf'
Received privsep req type 00 sz 1 on srvsock 13
Child proc 1710 exited with status 0

```
</details>

**Comment by aboulfad** [comment]
Not an sslsplit issue, but combination of improper usage of arp poisoning, pf and routing rules.
