### ISSUE TITLE
Q: Intra-LAN client to server sslsplit

### ISSUE THREAD

**Issue by aboulfad** [droe/sslsplit#213]
Hello,
can sslsplit intercept an SSL connection between a client (macos) and server (webos) both connected to the same LAN via a **switch/router** where sslsplit runs on the **same** host as the client ?

All services to be intercepted are on the LAN, and none of the pf rules I've added get sslsplit to detect any connection. This scenario is close to the one in issue #212 but without an iphone.

Thank you.

**Comment by aboulfad** [comment]
Similar to #214, to intercept traffic on intra LAN, traffic needs to be directed to a separate host/VM running sslsplit and setup the appropriate routing rules.

**Comment by droe** [comment]
It is not completely impossible, people have solved such or simular scenarios using advanced NAT rules differentiating SSLsplit upstream traffic from traffic to intercept in one way or other. This is not in scope for SSLsplit, we do not have the capability to support you on this, this would be better asked in the support communities of the redirection and NAT tools you are using.
