### ISSUE TITLE
SSLSPLIT doesnt do anything.

### ISSUE THREAD

**Issue by syrex1013** [droe/sslsplit#214]
Please supply the following with bug reports to allow for diagnostics:

-   Output of `sslsplit -V`
```
SSLsplit 0.5.2 (built 2018-03-31)
Copyright (c) 2009-2018, Daniel Roethlisberger <daniel@roe.ch>
https://www.roe.ch/SSLsplit
Build info: V:FILE
Features: -DHAVE_NETFILTER
NAT engines: netfilter* tproxy
netfilter: IP_TRANSPARENT IP6T_SO_ORIGINAL_DST
Local process info support: no
compiled against OpenSSL 1.1.0h  27 Mar 2018 (1010008f)
rtlinked against OpenSSL 1.1.0h  27 Mar 2018 (1010008f)
OpenSSL has support for TLS extensions
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
Using SSL_MODE_RELEASE_BUFFERS
SSL/TLS protocol availability: tls10 tls11 tls12 
SSL/TLS algorithm availability: !SHA0 RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.1.8-stable
rtlinked against libevent 2.1.8-stable
4 CPU cores detected
```
-   Output of `uname -a`
`Linux kali 4.17.0-kali1-amd64 #1 SMP Debian 4.17.8-1kali1 (2018-07-24) x86_64 GNU/Linux`
-   Exact command line arguments used to run `sslsplit`
`V -D -k  ca.key -c ca.crt -P  https 127.0.0.1 8443  https ::1 8443`
-   NAT redirection rules you are using, if applicable
```
iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8443
iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8443
```
For build problems, please supply:
So after running sslslip it starts and then waits at line.
`Starting main event loop.`
I'm opening https websites but nothing is sniffed

**Comment by sonertari** [comment]
It seems like your web traffic is *not* going through this system, hence SSLsplit. Are you sure SSLsplit is in between your browser and the Web, and there is no other way your browser can reach the web? How do you redirect web traffic to this system?

**Comment by droe** [comment]
Also, you redirect both port 80 and port 443 to the same SSLsplit proxyspec using https mode. You'll want to redirect port 80 to a http mode proxyspec.

**Comment by remix30303** [comment]
@sonertari I'm trying it on my browser on the same system.

**Comment by sonertari** [comment]
Yes, that's the issue. Your browser is reaching the web directly. SSLsplit should be running on a router (or a system acting like a router) in between your browser and the web.

Also don't forget to heed @droe's suggestion too.

**Comment by remix30303** [comment]
So i cant sniff my own requests? I must arpspoof someone?

**Comment by sonertari** [comment]
Short answer: You need to change your default route to achieve that.

I use a VM for that (and for other reasons irrelevant here). I run sslsplit on a system running in a VM, which also acts as a DHCP server and a router. The host system obtains an IP from this guest system. Then I set the default route of my host system to the the guest system, so that the guest system goes in between the host system and the Internet.

**Comment by remix30303** [comment]
Oh ok, thanks for help and in-depth explanation :D

**Comment by sonertari** [comment]
Does it work?

**Comment by remix30303** [comment]
Nope, sslsplit does not work.

**Comment by sonertari** [comment]
This is really about routing and netfilter rules, not sslsplit.

Perhaps if you use the following, sslsplit can get the packets: `sslsplit -D -k ca.key -c ca.crt -P https <ip of eth0> 8883 http <ip of eth0> 8880`

Or perhaps `sslsplit -D -k ca.key -c ca.crt -P https <ip of eth0> 443 http <ip of eth0> 80` as I don't think your netfilter (nat) rules are doing what you expect with those arpspoof lines.

**Comment by remix30303** [comment]
Hello,
I tried using both of commands that you suggested. Still sslsplit does nothing.

**Comment by droe** [comment]
If you use netcat in verbose mode to open ports 8880 and 8883 locally instead of sslsplit, does netcat receive connections?

**Comment by remix30303** [comment]
What do you mean by open ports with netcat? Is this correct command?
`netcat -l 8880`
If yes then no I dont receive any data.

**Comment by remix30303** [comment]
OK ive got it to work, sadly many sites use hsts so I get warning but i see traffic flowing in sslsplit :D
