### ISSUE TITLE
Missing Error Check in function SSL_CTX_use_certificate()

### ISSUE THREAD

**Issue by lc3412** [droe/sslsplit#224]
Function SSL_CTX_use_certificate() returns 1 on success. Otherwise need to check out the error stack to find out the reason. However , the return value of function SSL_CTX_use_certificate() is not checked on line 769. See the following code:

line: 769
https://github.com/droe/sslsplit/blob/19a16bd7aab5f01ebfc2410d21e5b34077445d64/pxyconn.c#L769-L775

==================================================================================

We find the return value of this call been checked in the same file
Such as,
line: 1146
https://github.com/droe/sslsplit/blob/19a16bd7aab5f01ebfc2410d21e5b34077445d64/pxyconn.c#L1146-L1147

Chi Li, Zuxing Gu, Jiecheng Wu

**Comment by sonertari** [comment]
Also in ssl.c on line 1269. SSL_CTX_use_certificate() is declared with `__warn_unused_result__` attribute, but interestingly compilers do not give any warning.

**Comment by droe** [comment]
Thank you for reporting this issue.
