### ISSUE TITLE
Missing Error Check in function SSL_CTX_use_PrivateKey()

### ISSUE THREAD

**Issue by lc3412** [droe/sslsplit#225]
Function SSL_CTX_use_PrivateKey() returns 1 on success. Otherwise need to check out the error stack to find out the reason. However , the return value of function SSL_CTX_use_PrivateKey() is not checked on line 770. See the following code:

line: 770
https://github.com/droe/sslsplit/blob/19a16bd7aab5f01ebfc2410d21e5b34077445d64/pxyconn.c#L770-L775

=================================================================================

We find the return value of this call been checked in the same file
Such as,
line: 1150
https://github.com/droe/sslsplit/blob/19a16bd7aab5f01ebfc2410d21e5b34077445d64/pxyconn.c#L1150-L1151

Chi Li, Zuxing Gu, Jiecheng Wu

**Comment by droe** [comment]
Thank you for reporting this issue.
