### ISSUE TITLE
dsthost/dstport_str may be NULL

### ISSUE THREAD

**Issue by sonertari** [droe/sslsplit#233]
I got the following message: `sslsplit: CRITICAL: vfprintf %s NULL in "%s disconnected to [%s]:%s "`. This is for line 2237 in pxyconn.c. I don't know what caused this error, perhaps intif went down at the start of that connection. But this message repeated 6 times within 50 seconds, so it happened to 6 different connections. Should we use STRORDASH() macro to prevent these messages? Otherwise, I guess they don't seem to affect the execution of sslsplit.

**Comment by droe** [comment]
I think you can reproduce that when forcing SSL errors early on, for example by doing a HTTP (without S) connection over a `https` proxyspec. `STRORDASH()` seems sensible, yes.
