### ISSUE TITLE
tcp ports in mirrored packets are different from original ports

### ISSUE THREAD

**Issue by schmilwenspire** [droe/sslsplit#247]
Hi,

I'm using version 0.5.4 and have encountered a problem with port mirroring.
The TCP ports on the mirrored packets are different than the one in original packets

Samuel

**Comment by sonertari** [comment]
@schmilwenspire Can you try the develop branch? Please report back if my last commit fixes the issue you have reported (it does here).

**Comment by sonertari** [comment]
Per @schmilwenspire's [confirmation message on Gitter](https://gitter.im/droe/sslsplit?at=5c693ac88328315dec0bbafd), I assume this issue has been fixed. Closing.
