### ISSUE TITLE
Makefile tries to install files outside of PREFIX

### ISSUE THREAD

**Issue by fxcoudert** [droe/sslsplit#251]
Trying to build sslsplit 0.5.4 as part of Homebrew fails because:

- we want to install inside `/usr/local` by passing `make install PREFIX=/usr/local`
- yet, the makefile tries to install into `/var/log` which is not user-writable on macOS

The issue comes from:

```
	test -d $(DESTDIR)/var/log/$(TARGET) || \
		$(MKDIR) -p $(DESTDIR)/var/log/$(TARGET)
	test -d $(DESTDIR)/var/run/$(TARGET) || \
		$(MKDIR) -p $(DESTDIR)/var/run/$(TARGET)
```

which is wrong, because `$(DESTDIR)/var/log` is not inside `PREFIX`. This is not expected behaviour. More importantly, we cannot fix `DESTDIR` instead of `PREFIX` because then `SUBSTITUTIONS` will fail to point to the right directories (it does not use `DESTDIR`).

**Comment by sonertari** [comment]
I have never tried to change the default install path, nor do I have an osx system, but I think you are right. So what happens when you change those lines to the following (making them similar to all other install/deinstall paths)?:
```
	test -d $(DESTDIR)$(PREFIX)/var/log/$(TARGET) || \
		$(MKDIR) -p $(DESTDIR)$(PREFIX)/var/log/$(TARGET)
	test -d $(DESTDIR)$(PREFIX)/var/run/$(TARGET) || \
		$(MKDIR) -p $(DESTDIR)$(PREFIX)/var/run/$(TARGET)
```
Can you try this and report back please? If it works for you, I can fix it on the develop branch.

**Comment by fxcoudert** [comment]
Yes, `$(DESTDIR)$(PREFIX)` is how it should be. That fixes the issue.

**Comment by droe** [comment]
Resolved by not creating those directories in the first place. Distributions with default configs depending on those directories should create them in their preferred location as part of their distribution packages.
