### ISSUE TITLE
Exit code is 1 whatever signal sent to terminate process

### ISSUE THREAD

**Issue by tomlabaude** [droe/sslsplit#252]
On Mac, exit code is most of time 1, even if stopping with CTRL+C, or terminating (SIGTERM) or killing it (SIGKILL), which makes it hard to catch errors for embedding scripts or programs.

Standard Error output sometimes mentions the signal received, but exit code was most of time observed being 1.

_Ex 1 - Killed by Signal 2 - SIGINT - CTRL+C:_
```
Child proc 86866 killed by signal 2
$ echo $?
1
```

_Ex 2 - Killed by Signal 9 - SIGKILL:_
```
Child proc 94363 killed by signal 9
$ echo $?
1
```

_Ex 3 - Killed by Signal 15 - SIGTERM:_
```
Child proc 13789 killed by signal 15
$ echo $?
1
```

Some articles suggests to increment exit code of 128+Signal:
https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html
http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF

---

For bug reports, please supply:

-   Output of `sslsplit -V`
```
SSLsplit 0.5.4 (built 2019-06-28)
Copyright (c) 2009-2018, Daniel Roethlisberger <daniel@roe.ch>
https://www.roe.ch/SSLsplit
Build info: OSX:10.14.5 XNU:4570.71.2:fallback:4903.261.4 V:DIR N:06fdafa
Features: -DHAVE_PF
NAT engines: pf*
Local process info support: no
compiled against OpenSSL 1.0.2 22 Jan 2015 (1000200f)
rtlinked against OpenSSL 1.0.2k  26 Jan 2017 (100020bf)
OpenSSL has support for TLS extensions
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
OpenSSL has engine support
Using SSL_MODE_RELEASE_BUFFERS
SSL/TLS protocol availability: ssl3 tls10 tls11 tls12 
SSL/TLS algorithm availability: SHA0 RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.1.8-stable
rtlinked against libevent 2.1.8-stable
compiled against libnet 1.1.6
rtlinked against libnet 1.1.6
compiled against libpcap n/a
rtlinked against libpcap 1.6.2
4 CPU cores detected
```

-   Output of `uname -a`
`Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64`

-   Exact command line arguments used to run `sslsplit`
`sudo ./sslsplit -k ~/cert.pem -L ~/logAllData.log -l ~/logConnections.log autossl 127.0.0.1 6971`

**Comment by droe** [comment]
This feature was merged to develop with #253 - feel free to comment in case that does not address your needs.
