### ISSUE TITLE
Build error with ubuntu server 18.04

### ISSUE THREAD

**Issue by wyssp8** [droe/sslsplit#258]
I have the following error while building:

root@interceptionproxy:/home/proxyuser/sslsplit# make
GNUmakefile:213: pkg-config not found - guessing paths/flags for dependencies

SSLsplit 0.5.5-1-g065f8cf

Report bugs at https://github.com/droe/sslsplit/issues/new
Please supply this header for diagnostics when reporting build issues
Before reporting bugs, make sure to try the latest develop branch first:
% git clone -b develop https://github.com/droe/sslsplit.git

Via pkg-config:
OPENSSL_BASE:   /usr
LIBEVENT_BASE:  /usr
LIBPCAP_BASE:   /usr
LIBNET_BASE:    /usr
Build options:  -DHAVE_NETFILTER
Build info:     V:GIT
uname -a:       Linux interceptionproxy 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

cc -c -isystem/usr/include -isystem/usr/include -isystem/usr/include -isystem/usr/include -D_GNU_SOURCE -D"PKGLABEL=\"SSLsplit\"" -DHAVE_NETFILTER -g  -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -O -o nat.o nat.c
/bin/sh: 1: cc: not found
GNUmakefile:491: recipe for target 'nat.o' failed
make: *** [nat.o] Error 127

root@interceptionproxy:/home/proxyuser/sslsplit# uname -a
Linux interceptionproxy 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

openssl is already the newest version (1.1.1-1ubuntu2.1~18.04.4).
libevent-dev is already the newest version (2.1.8-stable-4build1).

I took the newest version with git clone -b develop https://github.com/droe/sslsplit.git
Thanks for helping!

Kind regards
Patrick

**Comment by sonertari** [comment]
I think you don't have a C compiler installed. So install gcc and try again.

**Comment by wyssp8** [comment]
Yes you were right, sorry for that.

But now the build stucks here:

Via pkg-config:
OPENSSL_BASE:   /usr
LIBEVENT_BASE:  /usr
LIBPCAP_BASE:   /usr
LIBNET_BASE:    /usr
Build options:  -DHAVE_NETFILTER
Build info:     V:GIT
uname -a:       Linux interceptionproxy 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Lin

cc -c -isystem/usr/include -isystem/usr/include -isystem/usr/include -isystem/usr/include -D_GNU_SOURCE -D"PKGLABEL=\"SSLsplit\""ILTER -D"BUILD_PKGNAME=\"sslsplit\"" -D"BUILD_VERSION=\"0.5.5-1-g065f8cf\"" -D"BUILD_DATE=\"2019-09-18\"" -D"BUILD_INFO=\"V:GIT\"EATURES=\"-DHAVE_NETFILTER\"" -g  -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -O -o build
cc -L/usr/lib -L/usr/lib -L/usr/lib -L/usr/lib -pthread -o sslsplit cachemgr.o cert.o cachefkcrt.o opts.o proc.o cachetgcrt.o buigr.o main.o cache.o dynbuf.o sys.o proxy.o cachessess.o nat.o base64.o url.o ssl.o logbuf.o thrqueue.o logpkt.o log.o pxyconn.o pger.o cachedsess.o util.o -lssl -lcrypto -lz -levent -levent_openssl -levent_pthreads -lnet -lpcap
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
GNUmakefile:477: recipe for target 'sslsplit' failed
make: *** [sslsplit] Error 1

I hope that will be my last question

regards
Patrick

**Comment by sonertari** [comment]
I think you need to install zlib1g, since the linker cannot find -lz.

**Comment by wyssp8** [comment]
Thank you for your fast reply. zlib1g was already installed.

zlib1g is already the newest version (1:1.2.11.dfsg-0ubuntu2).
Still the same issue while building

regards
Patrick

**Comment by sonertari** [comment]
Do you have zlib1g-dev too?

**Comment by wyssp8** [comment]
Thank you a lot! Now it works. I close this issue.

regards
Patrick
