### ISSUE TITLE
Save traffic in PCAP format

### ISSUE THREAD

**Issue by jessicah** [droe/sslsplit#27]
Is it possible to add a logging option that saves traffic in a format readable by Wireshark? This would make dissecting binary protocols over SSL much easier to analyse.

**Comment by droe** [comment]
I am working on preparing sslsplit -L log post-processing scripts for inclusion in sslsplit. Stay tuned.

**Comment by mattes** [comment]
That's awesome news!

**Comment by droe** [comment]
Initial log file to PCAP conversion script added, closing this issue.
