### ISSUE TITLE
Server requires TLS 1.2 Client Hello - Error from bufferevent: 0:- 336109761:193:no shared cipher:20:SSL 

### ISSUE THREAD

**Issue by Apollo2342** [droe/sslsplit#30]
I get the following error when I try to read traffic from the Android App sayhey.
Error from bufferevent: 0:- 336109761:193:no shared cipher:20:SSL 
I use the Kali Linux with fully updated system.
The App gets no connection.

```
Generated RSA key for leaf certs.
SSLsplit 0.4.8-10-g85b177f (built 2014-09-02)
Copyright (c) 2009-2014, Daniel Roethlisberger <daniel@roe.ch>
http://www.roe.ch/SSLsplit
Features: -DDISABLE_SSLV2_SESSION_CACHE -DHAVE_NETFILTER
NAT engines: netfilter* tproxy
netfilter:  IP_TRANSPARENT SOL_IPV6 !IPV6_ORIGINAL_DST
compiled against OpenSSL 1.0.1e 11 Feb 2013 (1000105f)
rtlinked against OpenSSL 1.0.1e 11 Feb 2013 (1000105f)
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
Using SSL_MODE_RELEASE_BUFFERS
Using direct access workaround when loading certs
SSL/TLS algorithm availability: RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.0.19-stable
rtlinked against libevent 2.0.21-stable
4 CPU cores detected
proxyspecs:
- [0.0.0.0]:1025 tcp plain netfilter
- [0.0.0.0]:1050 ssl plain netfilter
- [0.0.0.0]:8443 ssl http netfilter
- [0.0.0.0]:8080 tcp http netfilter
Loaded CA: '/C=PortSwigger/ST=PortSwigger/L=PortSwigger/O=PortSwigger/OU=PortSwigger CA/CN=PortSwigger CA'
Using libevent backend 'epoll'
Event base supports: edge yes, O(1) yes, anyfd no
Inserted events:
  0x1056460 [fd 8] Read Persist
  0x1055fb0 [fd 9] Read Persist
  0x1057540 [fd 10] Read Persist
  0x1059190 [fd 11] Read Persist
  0x1059250 [fd 12] Read Persist
  0x1056298 [fd 7] Read Persist
  0x10592e0 [fd 3] Signal Persist
  0x1059520 [fd 1] Signal Persist
  0x1059650 [fd 2] Signal Persist
  0x1059780 [fd 13] Signal Persist
Initialized 8 connection handling threads
Started 8 connection handling threads
Starting main event loop.
SNI peek: [n/a] [complete]
Connecting to [85.88.17.243]:1235
SNI peek: [n/a] [complete]
Connecting to [85.88.17.243]:1235
===> Original server certificate:
Subject DN: /CN=foo.ssms.de
Common Names: foo.ssms.de
Fingerprint: 60:de:90:74:97:78:79:30:7b:5b:fb:c3:0d:36:d5:35:6f:04:bb:ab
Certificate cache: MISS
===> Forged server certificate:
Subject DN: /CN=foo.ssms.de
Common Names: foo.ssms.de
Fingerprint: 67:20:4e:97:d5:a6:14:40:30:7b:20:86:bc:5a:4f:7d:a3:aa:26:f9
ssl [192.168.3.131]:37806 [85.88.17.243]:1235 sni:- crt:foo.ssms.de origcrt:foo.ssms.de
Error from bufferevent: 0:- 336109761:193:no shared cipher:20:SSL routines:138:SSL3_GET_CLIENT_HELLO
SSL_free() in state 00002112 = SSL_ST_ACCEPT|0112 = 3RCH_C (SSLv3 read client hello C) [accept socket]
SSL_free() in state 00000003 = 0003 = SSLOK  (SSL negotiation finished successfully) [connect socket]
===> Original server certificate:
Subject DN: /CN=foo.ssms.de
Common Names: foo.ssms.de
Fingerprint: 60:de:90:74:97:78:79:30:7b:5b:fb:c3:0d:36:d5:35:6f:04:bb:ab
Certificate cache: HIT
===> Forged server certificate:
Subject DN: /CN=foo.ssms.de
Common Names: foo.ssms.de
Fingerprint: 67:20:4e:97:d5:a6:14:40:30:7b:20:86:bc:5a:4f:7d:a3:aa:26:f9
ssl [192.168.3.131]:37807 [85.88.17.243]:1235 sni:- crt:foo.ssms.de origcrt:foo.ssms.de
Error from bufferevent: 0:- 336109761:193:no shared cipher:20:SSL routines:138:SSL3_GET_CLIENT_HELLO
SSL_free() in state 00002112 = SSL_ST_ACCEPT|0112 = 3RCH_C (SSLv3 read client hello C) [accept socket]
SSL_free() in state 00000003 = 0003 = SSLOK  (SSL negotiation finished successfully) [connect socket]
SNI peek: [n/a] [complete]
Connecting to [74.125.230.101]:443
...
```

**Comment by noelsmith** [comment]
I am receiving this exact same error message running the latest version of SSLSplit, compiled with the latest version of OpenSSL.  I tried the "-r tls12" flag but keep getting the same error.  My SSLSplit log is below:

    Generated RSA key for leaf certs.
    SSLsplit master (built 2015-04-09)
    Copyright (c) 2009-2014, Daniel Roethlisberger <daniel@roe.ch>
    http://www.roe.ch/SSLsplit
    Build info: V:DIR
    Features: -DHAVE_NETFILTER
    NAT engines: netfilter* tproxy
    netfilter: IP_TRANSPARENT SOL_IPV6 !IPV6_ORIGINAL_DST
    Local process info support: no
    compiled against OpenSSL 1.0.2a 19 Mar 2015 (1000201f)
    rtlinked against OpenSSL 1.0.1e 11 Feb 2013 (1000105f)
    TLS Server Name Indication (SNI) supported
    OpenSSL is thread-safe with THREADID
    Using SSL_MODE_RELEASE_BUFFERS
    SSL/TLS protocol availability: ssl3 tls10 tls11 tls12 
    SSL/TLS algorithm availability: RSA DSA ECDSA DH ECDH EC
    OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET    
    SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION 
    SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS  
    SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
    compiled against libevent 2.0.22-stable
    rtlinked against libevent 2.0.19-stable
    2 CPU cores detected
    SSL/TLS protocol: negotiate
    proxyspecs:
    - [0.0.0.0]:8443 ssl http netfilter
    Loaded CA: '/C=US/ST=NY/L=New York/O=Internet Widgits Pty Ltd/CN=SIFT'
    Using libevent backend 'epoll'
    Event base supports: edge yes, O(1) yes, anyfd no
    Inserted events:
    0x82a1ec8 [fd 7] Read Persist
    0x82a3c94 [fd 8] Read Persist
    0x82a1db8 [fd 6] Read Persist
    0x82a3ce0 [fd 3] Signal Persist
    0x82a3fe0 [fd 1] Signal Persist
    0x82a40c0 [fd 2] Signal Persist
    0x82a41a0 [fd 13] Signal Persist
    Initialized 4 connection handling threads
    Started 4 connection handling threads
    Starting main event loop.
    SNI peek: [REDACTED] [complete]
    Connecting to [54.88.41.174]:443
    ===> Original server certificate:
    Subject DN: /C=US/ST=Virginia/L=Chantilly/O=Excivity, Inc./CN=*.excivity.com
    Common Names: *.excivity.com/*.excivity.com/excivity.com
    Fingerprint: 0e:0b:cd:be:b0:09:e0:50:94:40:c2:31:12:ee:de:a8:3a:38:24:18
    Certificate cache: MISS
    ===> Forged server certificate:
    Subject DN: /C=US/ST=Virginia/L=Chantilly/O=Excivity, Inc./CN=*.excivity.com
    Common Names: *.excivity.com/*.excivity.com/excivity.com
    Fingerprint: 21:57:02:80:bf:7b:0d:8a:fb:b6:10:d3:eb:52:18:91:74:3d:1f:16
    SSL connected to [54.88.41.174]:443 TLSv1.2 ECDHE-RSA-AES256-SHA
    Certificate cache: KEEP (SNI match or target mode)
    Error from bufferevent: 0:- 336109761:193:no shared cipher:20:SSL    
    routines:138:SSL3_GET_CLIENT_HELLO
    SSL disconnected to [54.88.41.174]:443
    SSL disconnected from [10.0.0.1]:33081
    SSL_free() in state 00002112 = SSL_ST_ACCEPT|0112 = 3RCH_C (SSLv3 read client hello C)   
    [accept socket]
    SSL_free() in state 00000003 = 0003 = SSLOK  (SSL negotiation finished successfully) [connect  
    socket]
    ^CReceived signal 2
    Main event loop stopped.

**Comment by droe** [comment]
@noelsmith Please create a new issue for the problem you are experiencing. `no shared cipher` from OpenSSL simply indicates that the handshake failed to result in a protocol version or cipher suite supported by both client and server. There are countless potential reasons for that to happen, including the version mismatch of OpenSSL that you appear to be having (built against 1.0.2 but running with 1.0.1).
