### ISSUE TITLE
Error 24 on listener

### ISSUE THREAD

**Issue by noiala** [droe/sslsplit#31]
Sslsplit installed just fine and also starts without any issue.
When I hit enter on the client browser it goes:
....
....
Connecting to [192.168.1.10]:8080
Connecting to [192.168.1.10]:8080
Error 24 on listener: Too many open files
Main event loop stopped.
Error from bufferevent: 104:Connection reset by peer 0:0:-:0:-:0:-
Segmentation fault (core dumped)

The "connecting to IP" line repeats several times.

sslsplit -V:
SSLsplit 0.4.8-10-g85b177f (built 2014-10-01)
Copyright (c) 2009-2014, Daniel Roethlisberger daniel@roe.ch
http://www.roe.ch/SSLsplit
Features: -DDISABLE_SSLV2_SESSION_CACHE -DHAVE_NETFILTER
NAT engines: netfilter\* tproxy
netfilter:  IP_TRANSPARENT SOL_IPV6 !IPV6_ORIGINAL_DST
compiled against OpenSSL 1.0.1f 6 Jan 2014 (1000106f)
rtlinked against OpenSSL 1.0.1f 6 Jan 2014 (1000106f)
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
Using SSL_MODE_RELEASE_BUFFERS
SSL/TLS algorithm availability: RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.0.21-stable
rtlinked against libevent 2.0.21-stable
2 CPU cores detected

Not sure what I'm doing wrong here.

Thx.

**Comment by arinc9** [comment]
Looking at this issue years later, using owner module to differentiate the traffic makes sense. Maybe marking the sslsplit traffic could be another solution? Adding an option to set a fwmark on sslsplit traffic so the marked traffic won't be caught by the REDIRECT rule we put.

For anyone looking for an easy way out:
Run sslsplit as root.
```
iptables -t nat -A OUTPUT -d <attackedIP> -p tcp -m owner --gid-owner <yourUserName> --dport 443 -j REDIRECT --to-ports 8443
```
