### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [droe/sslsplit#38]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html) ⇒ [main_version](https://github.com/droe/sslsplit/blob/ecbc84438ae88452357eeeddfcc630f2318914cc/main.c#L63)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html) ⇒ [thrqueue_new](https://github.com/droe/sslsplit/blob/47c409cbb5fbc8a6041e5e7f04abec4d0d221011/thrqueue.c#L52)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html) ⇒ [proxyspec_parse](https://github.com/droe/sslsplit/blob/79c67ebed7b3fa653a7b6c01b7bcb93050ea44e1/opts.c#L124)

**Comment by elfring** [comment]
Would you like to look once more at any remaining update candidates?
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [cert_new](https://github.com/droe/sslsplit/blob/7677fe06557509e95e548318909c1a328b6f6069/cert.c#L38)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [sys_user_str](https://github.com/droe/sslsplit/blob/7677fe06557509e95e548318909c1a328b6f6069/sys.c#L240)

**Comment by droe** [comment]
I will commit a fix for the first one, thanks. The second one is bogus; if strdup() fails, it returns NULL, which means sys_user_str() returns NULL, which in turn signals an error to the caller.

**Comment by elfring** [comment]
How do you think about to care also for a failed string copy operation?

**Comment by droe** [comment]
Feel free to submit as many fixes as pull requests as you can.

**Comment by droe** [comment]
I am starting to wonder whether you are actually some kind of ELIZA specialized on suggesting code improvements. Can you submit at least a single valid pull request to prove that you are actually a human being capable of contributing code?

**Comment by elfring** [comment]
>… some kind of ELIZA …

You can also notice (if you look around a bit more) that I contributed some concrete patches for various free software.
It can occasionally happen that this software will be fixed quicker by other contributors (than me).

Thanks for [another small source code improvement](https://github.com/droe/sslsplit/commit/29fb4ee0fdafca355835431f86041afad418fb91 "Add error handling to all pthread_mutex_init instances").
Unfortunately, there are [still more update candidates left over](https://github.com/droe/sslsplit/blob/7677fe06557509e95e548318909c1a328b6f6069/thrqueue.c#L104 "More exception handling in thrqueue_…()?")

**Comment by droe** [comment]
`thrqueue_enqueue()` is a wont-fix, because those functions cannot fail under reasonable conditions. In my eyes, the cost/benefit ratio is not in favour of adding unneeded dead code and complexity there.

**Comment by elfring** [comment]
Do you like any reminders for the incomplete error detection (and corresponding exception handling) more from other contributors (or automatic source code analysis tools)?

**Comment by droe** [comment]
I'm afraid that I don't understand your question. I always welcome specific and thoughtful bug reports, regardless from whom.
