### ISSUE TITLE
Improve handling of renegotiation and client cert authentication

### ISSUE THREAD

**Issue by droe** [droe/sslsplit#46]
Handle renegotiations and client certificate authentication more gracefully.

**Comment by droe** [comment]
In #173, @BNET-williamsollers suggests to partially solve this by allowing a default client certificate to be specified, to be used whenever a server asks for client auth.

**Comment by naf419** [comment]
I tried to implement @BNET-williamsollers suggestion of a default client certificate to be specified on the command line.
