### ISSUE TITLE
Error while writing full data content log to a file

### ISSUE THREAD

**Issue by vmarteev** [droe/sslsplit#65]
Firstly, thanks for a great tool.
I'm experiencing a problem when I choose to write content log to a file.

I run sslsplit with following command:
`./sslsplit -D -l ./connections.log -L ./connections_data.log -k my.key -c my.crt ssl 127.0.0.1 8443`

It results in the following error message and nothing works:

Error from ioctl(DIOCNATLOOK): Operation not permitted
Connection not found in NAT state table, aborting connection

However, when I run sslsplit with:

`./sslsplit -D -l ./connections.log -S ./logdir -k my.key -c my.crt ssl 127.0.0.1 8443`

It works fine!
What I'm doing wrong?

Thanks.

**Comment by rajhlinux** [comment]
i also get 

"Connection not found in NAT state table, aborting connection"

This is what I use on terminal:
`sslsplit -k ca.key -c ca.crt -D -l connect.log -S logdir -L sslsplit.log https 127.0.0.1 10443 http 127.0.0.1 10080`

On FreeBSD 13.1

`# sslsplit -V`

```
SSLsplit 0.5.5 (built 2023-02-20)
Copyright (c) 2009-2019, Daniel Roethlisberger <daniel@roe.ch>
https://www.roe.ch/SSLsplit
Build info: V:FILE HDIFF:0 N:83c4edf
Features: -DHAVE_IPFILTER -DHAVE_IPFW -DHAVE_PF
NAT engines: pf* ipfw ipfilter
ipfilter: version 5010200
Local process info support: yes (FreeBSD sysctl)
compiled against OpenSSL 1.1.1o-freebsd  3 May 2022 (101010ff)
rtlinked against OpenSSL 1.1.1o-freebsd  3 May 2022 (101010ff)
OpenSSL has support for TLS extensions
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
OpenSSL has engine support
Using SSL_MODE_RELEASE_BUFFERS
SSL/TLS protocol availability: tls10 tls11 tls12 
SSL/TLS algorithm availability: !SHA0 RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.1.12-stable
rtlinked against libevent 2.1.12-stable
compiled against libnet 1.2
rtlinked against libnet 1.2
compiled against libpcap n/a
rtlinked against libpcap 1.9.1
8 CPU cores detected
```

`uname -a`

`FreeBSD user.user.user 13.1-RELEASE-p3 FreeBSD 13.1-RELEASE-p3 GENERIC amd64`

Thanks.

**Comment by sonertari** [comment]
That usually happens if you cannot redirect traffic to sslsplit properly. Please read [the man page](https://github.com/droe/sslsplit/blob/develop/sslsplit.1.in) paragraph starting with "SSLsplit does not automagically redirect any network traffic.", if you haven't yet.
