### ISSUE TITLE
Manpage: Listen on 0.0.0.0 by default?

### ISSUE THREAD

**Issue by fd0** [droe/sslsplit#75]
The section EXAMPLES of the man page recommends running SSLsplit as follows:

       sslsplit -k ca.key -c ca.crt -l connect.log -L /tmp \
		https ::1 10443  https 127.0.0.1 10443 \
		http  ::1 10080  http  127.0.0.1 10080

This didn't work for me while running Linux and redirecting with netfilter, I had to listen on `0.0.0.0` instead of `127.0.0.1` and it took me a long while to figure this out. The system behaved very strange: For all connections to port 80 and 443, the system responded with a RST packet instantly, and sslsplit did't output anything at all.

Maybe recommend listening on `0.0.0.0` instead (or add a paragraph about that)?

**Comment by droe** [comment]
Can you provide the relevant parts of your Netfilter configuration you used along with this and how you tested it? Is this in a dual-stack or v4-only setup?

I'm not convinced that changing the listener from localhost to all interfaces was what fixed your problem. From your problem description, I suspect something was/is wrong with your Netfilter setup.

**Comment by fd0** [comment]
Thanks for responding. It was an ipv4-only setup: Machine with two network interfaces: eth0 (uplink) and eth1 (192.168.1.1/24, wifi-accesspoint attached), configured for NAT.

The redirect was done via iptables:

    iptables -t nat -A PREROUTING -s 192.168.1.0/24 -p tcp --dport  80 -j REDIRECT --to-ports 10080
    iptables -t nat -A PREROUTING -s 192.168.1.0/24 -p tcp --dport 443 -j REDIRECT --to-ports 10443

SSLsplit was first started like this:

    ./sslsplit -k ca.key -c ca.crt -S /tmp/ \
        https 127.0.0.1 10443 \
        http  127.0.0.1 10080

Starting `tcpdump` on eth1 revealed that all connections were immediately answered with RST packets. Starting SSLstrip like this (and changing nothing else) fixed it:

    ./sslsplit -k ca.key -c ca.crt -S /tmp/ \
        https 0.0.0.0 10443 \
        http  0.0.0.0 10080

The setup is still available, can I test something else here?

**Comment by droe** [comment]
Thanks for the complete picture. So REDIRECT redirects to the IP address of the incoming interface, or 127.0.0.1 for locally generated packets. Yes, I guess that should be clarified.

Since it is a limitation specific to Linux REDIRECT I don't want to change the platform-independent example from loopback to all interfaces. I would propose a short explanation what address that SSLsplit will need to listen on when using REDIRECT. Feel free to submit a pull req with a proposal, otherwise I'll take care of it some other day.

**Comment by fd0** [comment]
Thanks, I created a pull request in #76

**Comment by droe** [comment]
Pull request #76 merged into `develop` in 0ebfcc9, closing issue as resolved. Thank you for your contribution!
