### ISSUE TITLE
Compilation warning on NetBSD

### ISSUE THREAD

**Issue by 0-wiz-0** [droe/sslsplit#78]
When compiling the 0.4.10 release on NetBSD-7.99.5/amd64, I get:
````
opts.c: In function 'proxyspec_parse':
opts.c:380:8: warning: 'af' may be used uninitialized in this function [-Wmaybe-uninitialized]
     af = sys_sockaddr_parse(&spec->connect_addr,
        ^
opts.c:316:8: warning: 'addr' may be used uninitialized in this function [-Wmaybe-uninitialized]
     af = sys_sockaddr_parse(&spec->listen_addr,
        ^
````

There's a NetBSD package available now, see
http://pkgsrc.se/security/sslsplit (in a couple of hours)

**Comment by droe** [comment]
The state machine ensures that af and addr are written to before they are being read, but I added explicit initializations to the `develop` branch now anyway to silence the compiler warnings. Thanks for the report and NetBSD porting/packaging.
