### ISSUE TITLE
Allow configurable user/group ownership for install

### ISSUE THREAD

**Issue by sheurich** [droe/sslsplit#81]
When porting to a packaging system like homebrew, configuration of user/group ownership during installation is desirable. At the moment, a patch to remove '-u 0 -g 0' from GNUmakefile is needed for a homebrew formula. Use of environment variables to override a default of UID 0, GID 0 would eliminate patching in this case.

**Comment by droe** [comment]
Most packaging systems only use the shipped make file for building but not installing, so this wasn't so much of an issue before. That being said, I added variables to override uid, gid and mode of installed files (but not directories) in a14354d on the `develop` branch. This will make it into the next release, probably 0.5.0, or in case another maintenance release will be necessary, into 0.4.12.

Thanks for letting me know what needed to be patched for homebrew!

**Comment by sheurich** [comment]
Sure, thanks @droe. The formula I just added is https://github.com/sheurich/homebrew/commit/0117ec85d9b22642146e363cfbbe11bc77c18f53.
