### ISSUE TITLE
Building a statically linked binary

### ISSUE THREAD

**Issue by kickwindbg** [droe/sslsplit#82]
Hi droe 
when i compile sslsplit static by replace $(CC)  with gcc -static in GNUMakeFile , I got the following error message

    gcc -static  -pthread -o sslsplit base64.o cache.o cachedsess.o cachefkcrt.o cachemgr.o cachessess.o cachetgcrt.o cert.o dynbuf.o logbuf.o log.o logger.o main.o nat.o opts.o proc.o proxy.o pxyconn.o pxysslshut.o pxythrmgr.o ssl.o sys.o thrqueue.o url.o util.o version.o -ldl -lssl -lcrypto -levent_openssl -levent_pthreads -levent  
    sys.o: In function `sys_privdrop':
    /home/test/Downloads/sslsplit-master/sys.c:97: warning: Using 'initgroups' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    /home/test/Downloads/sslsplit-master/sys.c:79: warning: Using 'getgrnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    sys.o: In function `sys_group_str':
    /home/test/Downloads/sslsplit-master/sys.c:278: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    sys.o: In function `sys_privdrop':
    /home/test/Downloads/sslsplit-master/sys.c:87: warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    /home/test/Downloads/sslsplit-master/sys.c:139: warning: Using 'endpwent' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    sys.o: In function `sys_user_str':
    /home/test/Downloads/sslsplit-master/sys.c:225: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    /usr/lib/i386-linux-gnu//libevent.a(evutil.o): In function `test_for_getaddrinfo_hacks':
    (.text+0x12f): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    /usr/lib/i386-linux-gnu//libevent.a(evutil.o): In function `evutil_getaddrinfo_common':
    (.text+0x1730): warning: Using 'getprotobynumber' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
    /usr/lib/i386-linux-gnu//libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
    (.text+0x15): undefined reference to `dlopen'
    /usr/lib/i386-linux-gnu//libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
    (.text+0x2b): undefined reference to `dlsym'
    /usr/lib/i386-linux-gnu//libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
    (.text+0x35): undefined reference to `dlclose'
    /usr/lib/i386-linux-gnu//libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
    (.text+0x381): undefined reference to `dlsym'
    /usr/lib/i386-linux-gnu//libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
    (.text+0x460): undefined reference to `dlerror'
    /usr/lib/i386-linux-gnu//libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
    (.text+0x4e1): undefined reference to `dlsym'
    /usr/lib/i386-linux-gnu//libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
    (.text+0x5c0): undefined reference to `dlerror'
    /usr/lib/i386-linux-gnu//libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
    (.text+0x630): undefined reference to `dlopen'
    /usr/lib/i386-linux-gnu//libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
    (.text+0x6a0): undefined reference to `dlclose'
    /usr/lib/i386-linux-gnu//libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
    (.text+0x6df): undefined reference to `dlerror'
    /usr/lib/i386-linux-gnu//libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
    (.text+0x788): undefined reference to `dladdr'
    /usr/lib/i386-linux-gnu//libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
    (.text+0x7d9): undefined reference to `dlerror'
    /usr/lib/i386-linux-gnu//libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
    (.text+0x834): undefined reference to `dlclose'
    collect2: error: ld returned 1 exit status
    make: *** [sslsplit] Error 1

i add the -ldl in the LDFLAGS  but not work

**Comment by droe** [comment]
You need to link against the indirect dependencies of all the libraries you are statically linking against.

Try adding `--static` to all the pkg-config invocations. If after that you still need to add more libraries, add the flags to `LIBS`, not `LDFLAGS`, e.g. `LIBS='-ldl' make`. This is due to flag ordering requirements of GCC. Let us know what worked; I'm considering to add support for static linking to the make file at some point so the feedback is valuable.

**Comment by kickwindbg** [comment]
Hi droe It works when i add -ldl at the end of here :
$(TARGET).test: $(TOBJS)
gcc -static $(LDFLAGS) $(TPKG_LDFLAGS) -o $@ $^ $(LIBS) $(TPKG_LIBS) -ldl
$(TARGET): $(OBJS)
gcc -static $(LDFLAGS) -o $@ $^ $(LIBS) -ldl

the -ldl should after the libcrypto, not before(not work)

BTW , can you give me the example how to set the args of natengine|targetaddr+port
proxyspec = type listenaddr+port [natengine|targetaddr+port|"sni"+port]

tks for your reply

root@ubuntu:/home/test/Downloads/sslsplit-master# make
SSLsplit master
via pkg-config: openssl libevent libevent_openssl libevent_pthreads
Build options: -DHAVE_NETFILTER
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o logbuf.o logbuf.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o cert.o cert.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o cachefkcrt.o cachefkcrt.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o opts.o opts.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o thrqueue.o thrqueue.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o log.o log.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o pxythrmgr.o pxythrmgr.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o pxysslshut.o pxysslshut.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o logger.o logger.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o nat.o nat.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o base64.o base64.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o version.o version.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o cachedsess.o cachedsess.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o main.o main.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o url.o url.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o util.o util.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o cache.o cache.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o dynbuf.o dynbuf.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o sys.o sys.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o pxyconn.o pxyconn.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o proxy.o proxy.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o cachetgcrt.o cachetgcrt.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o proc.o proc.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o ssl.o ssl.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o cachessess.o cachessess.c
gcc -static -c -D_GNU_SOURCE -D"BNAME=\"sslsplit\"" -D"PNAME=\"SSLsplit\"" -D"VERSION=\"master\"" -D"BUILD_DATE=\"2015-03-22\"" -D"FEATURES=\"-DHAVE_NETFILTER\"" -D"BUILD_INFO=\"V:DIR\"" -DHAVE_NETFILTER -g -pthread -std=c99 -Wall -Wextra -pedantic -D_FORTIFY_SOURCE=2 -fstack-protector-all -pthread -o cachemgr.o cachemgr.c
gcc -static -pthread -o sslsplit logbuf.o cert.o cachefkcrt.o opts.o thrqueue.o log.o pxythrmgr.o pxysslshut.o logger.o nat.o base64.o version.o cachedsess.o main.o url.o util.o cache.o dynbuf.o sys.o pxyconn.o proxy.o cachetgcrt.o proc.o ssl.o cachessess.o cachemgr.o -lssl -lcrypto -levent_openssl -levent_pthreads -levent -ldl
/usr/lib/gcc/i686-linux-gnu/4.9/../../../i386-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0xa): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
sys.o: In function `sys_privdrop':
/home/test/Downloads/sslsplit-master/sys.c:97: warning: Using 'initgroups' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/home/test/Downloads/sslsplit-master/sys.c:79: warning: Using 'getgrnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
sys.o: In function `sys_group_str':
/home/test/Downloads/sslsplit-master/sys.c:278: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
sys.o: In function `sys_privdrop':
/home/test/Downloads/sslsplit-master/sys.c:87: warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/home/test/Downloads/sslsplit-master/sys.c:139: warning: Using 'endpwent' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
sys.o: In function `sys_user_str':
/home/test/Downloads/sslsplit-master/sys.c:225: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/i686-linux-gnu/4.9/../../../i386-linux-gnu/libevent.a(evutil.o): In function `test_for_getaddrinfo_hacks':
(.text+0x15e): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/i686-linux-gnu/4.9/../../../i386-linux-gnu/libevent.a(evutil.o): In function `evutil_getaddrinfo_common':
(.text+0x1809): warning: Using 'getprotobynumber' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
root@ubuntu:/home/test/Downloads/sslsplit-master# ls
attrib.h cachedsess.c cachefkcrt.t.c cachessess.c cachetgcrt.t.c dynbuf.o logbuf.h log.o NEWS.md proc.o pxysslshut.c README.md sys.c url.c util.t.c
base64.c cachedsess.h cache.h cachessess.h cert.c dynbuf.t.c logbuf.o main.c opts.c proxy.c pxysslshut.h ssl.c sys.h url.h version.c
base64.h cachedsess.o cachemgr.c cachessess.o cert.h extra log.c main.o opts.h proxy.h pxysslshut.o ssl.h sys.o url.o version.h
base64.o cachedsess.t.c cachemgr.h cachessess.t.c cert.o GNUmakefile logger.c main.t.c opts.o proxy.o pxythrmgr.c ssl.o sys.t.c url.t.c version.o
base64.t.c cachefkcrt.c cachemgr.o cachetgcrt.c cert.t.c khash.h logger.h nat.c opts.t.c pxyconn.c pxythrmgr.h sslsplit thrqueue.c util.c xnu
BSDmakefile cachefkcrt.h cachemgr.t.c cachetgcrt.h dynbuf.c LICENSE logger.o nat.h proc.c pxyconn.h pxythrmgr.o sslsplit.1 thrqueue.h util.h
cache.c cachefkcrt.o cache.o cachetgcrt.o dynbuf.h logbuf.c log.h nat.o proc.h pxyconn.o pxythrmgr.t.c ssl.t.c thrqueue.o util.o
root@ubuntu:/home/test/Downloads/sslsplit-master# ./sslsplit
./sslsplit: no proxyspec specified.
root@ubuntu:/home/test/Downloads/sslsplit-master# ./sslsplit -h
Usage: sslsplit [options...] [proxyspecs...]
-c pemfile use CA cert (and key) from pemfile to sign forged certs
-k pemfile use CA key (and cert) from pemfile to sign forged certs
-C pemfile use CA chain from pemfile (intermediate and root CA certs)
-K pemfile use key from pemfile for leaf certs (default: generate)
-t certdir use cert+chain+key PEM files from certdir to target all sites
matching the common names (non-matching: generate if CA)
-O deny all OCSP requests on all proxyspecs
-P passthrough SSL connections if they cannot be split because of
client cert auth or no matching cert and no CA (default: drop)
-g pemfile use DH group params from pemfile (default: keyfiles or auto)
-G curve use ECDH named curve (default: secp160r2 for non-RSA leafkey)
-Z disable SSL/TLS compression on all connections
-r proto only support one of ssl3 tls10 tls11 tls12 (default: all)
-R proto disable one of ssl3 tls10 tls11 tls12 (default: none)
-s ciphers use the given OpenSSL cipher suite spec (default: ALL:-aNULL)
-e engine specify default NAT engine to use (default: netfilter)
-E list available NAT engines and exit
-u user drop privileges to user (default if run as root: nobody)
-m group when using -u, override group (default: primary group of user)
-j jaildir chroot() to jaildir (impacts -S/-F and sni, see manual page)
-p pidfile write pid to pidfile (default: no pid file)
-l logfile connect log: log one line summary per connection to logfile
-L logfile content log: full data to file or named pipe (excludes -S/-F)
-S logdir content log: full data to separate files in dir (excludes -L/-F)
-F pathspec content log: full data to sep files with % subst (excl. -L/-S):
%T - initial connection time as an ISO 8601 UTC timestamp
%d - dest address:port
%s - source address:port
%% - literal '%'
e.g. "/var/log/sslsplit/%T-%s-%d.log"
-d daemon mode: run in background, log error messages to syslog
-D debug mode: run in foreground, log debug messages on stderr
-V print version information and exit
-h print usage information and exit
proxyspec = type listenaddr+port [natengine|targetaddr+port|"sni"+port]
e.g. http 0.0.0.0 8080 www.roe.ch 80 # http/4; static hostname dst
https ::1 8443 2001:db8::1 443 # https/6; static address dst
https 127.0.0.1 9443 sni 443 # https/4; SNI DNS lookups
tcp 127.0.0.1 10025 # tcp/4; default NAT engine
ssl 2001:db8::2 9999 pf # ssl/6; NAT engine 'pf'
Example:
sslsplit -k ca.key -c ca.pem -P https 127.0.0.1 8443 https ::1 8443

At 2015-03-23 18:13:04, "Daniel Roethlisberger" <notifications@github.com> wrote:


You need to link against the indirect dependencies of all the libraries you are statically linking against.

Try adding --static to all the pkg-config invocations. If after that you still need to add more libraries, add the flags to LIBS, not LDFLAGS, e.g. LIBS='-ldl' make. This is due to flag ordering requirements of GCC. Let us know what worked; I'm considering to add support for static linking to the make file at some point so the feedback is valuable.

**Comment by droe** [comment]
What is the output of `pkg-config --libs --static openssl` on your system?

**Comment by droe** [comment]
For the record, I checked on an Ubuntu and the result includes the missing `-ldl`:
    $ pkg-config --libs --static openssl
    -lssl -lcrypto -ldl
So adding `--static` to the `pkg-config` invocations should solve the issue if your libraries are picked up through `pkg-config`.

**Comment by droe** [comment]
Note that you can successfully build statically with the following make invocation:

    % PKGCONFIG='pkg-config --static' CFLAGS='-static' LDFLAGS='-static' make

I will commit a change to the make file very soon which will make this cleaner still:

    % PCFLAGS='--static' CFLAGS='-static' LDFLAGS='-static' make

**Comment by droe** [comment]
As for examples for the syntax, check the sslsplit(1) manual page or the various blog entries linked from the SSLsplit web site.

**Comment by kickwindbg** [comment]
thanks for your reply, the examples for the syntax in sslsplit(1) manual is detailed, I should read it before ask
