### ISSUE TITLE
Failed to Hold the connection between S and C by parament -t with certificate chain

### ISSUE THREAD

**Issue by kickwindbg** [droe/sslsplit#84]
the certificate chain i created 
cat ca.key ca.crt >>ca.pem
cat ssl.key ssl.crt ca.crt >> ssl.pem
copy ca.pem ssl.pem to path /tmp/sslsplit/certs
sslsplit -t /tmp/sslsplit/certs -l connect.log -j /tmp/sslsplit -S logdir ssl 0.0.0.0 8443
the client send client_hello  then send RST close the connection
and sslsplit can analyze the server certificate 
But the connection is closed

**Comment by droe** [comment]
I will need additional information to be able to figure out what is happening. Can you provide what is listed under «Reporting Bugs» plus the relevant debug mode output:
https://github.com/droe/sslsplit/blob/develop/HACKING.md#reporting-bugs

**Comment by kickwindbg** [comment]
The debug console as follows:
# sslsplit -D -l connect.log -S /tmp/sslsplit/logdir -t /tmp/sslsplit/cert ssl 0.0.0.0 8443 tcp 0.0.0.0 8080
SSLsplit  (built 2014-05-26)
Copyright (c) 2009-2014, Daniel Roethlisberger <daniel@roe.ch>
http://www.roe.ch/SSLsplit
Features: -DDISABLE_SSLV2_SESSION_CACHE -DHAVE_NETFILTER
NAT engines: netfilter* tproxy
netfilter:  IP_TRANSPARENT SOL_IPV6 !IPV6_ORIGINAL_DST
compiled against OpenSSL 1.0.1e 11 Feb 2013 (1000105f)
rtlinked against OpenSSL 1.0.1e 11 Feb 2013 (1000105f)
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
Using SSL_MODE_RELEASE_BUFFERS
Using direct access workaround when loading certs
SSL/TLS algorithm availability: RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.0.19-stable
rtlinked against libevent 2.0.19-stable
1 CPU cores detected
proxyspecs:
- [0.0.0.0]:8080 tcp plain netfilter
- [0.0.0.0]:8443 ssl plain netfilter
No CA loaded.
Using libevent backend 'epoll'
Event base supports: edge yes, O(1) yes, anyfd no
Targets for '/tmp/sslsplit/cert/ca.pem': 'test'
Targets for '/tmp/sslsplit/cert/server.pem': 'test'
Inserted events:
  0x96617b8 [fd 7] Read Persist
  0x9661ba4 [fd 8] Read Persist
  0x9661f14 [fd 9] Read Persist
  0x96616a8 [fd 6] Read Persist
  0x9661f60 [fd 3] Signal Persist
  0x96620c8 [fd 1] Signal Persist
  0x96621a8 [fd 2] Signal Persist
  0x96622a8 [fd 13] Signal Persist
Initialized 2 connection handling threads
Started 2 connection handling threads
Starting main event loop.
SNI peek: [mail.126.com] [complete]
Connecting to [220.181.15.150]:443
===> Original server certificate:
Subject DN: /C=CN/ST=Zhejiang/L=Hangzhou/O=NetEase (Hangzhou) Network Co., Ltd/OU=Mail Dept./CN=*.126.com
Common Names: *.126.com/*.126.com/126.com
Fingerprint: cf:7f:94:85:dd:c0:cc:08:94:a0:89:46:b1:d5:c6:32:78:31:14:85
SNI peek: [mail.126.com] [complete]
Attempt reuse dst SSL session
Connecting to [220.181.15.150]:443
SSL_free() in state 00000003 = 0003 = SSLOK  (SSL negotiation finished successfully) [connect socket]
===> Original server certificate:
Subject DN: /C=CN/ST=Zhejiang/L=Hangzhou/O=NetEase (Hangzhou) Network Co., Ltd/OU=Mail Dept./CN=*.126.com
Common Names: *.126.com/*.126.com/126.com
Fingerprint: cf:7f:94:85:dd:c0:cc:08:94:a0:89:46:b1:d5:c6:32:78:31:14:85
SNI peek: [n/a] [complete]
Connecting to [220.181.15.150]:443
SSL_free() in state 00000003 = 0003 = SSLOK  (SSL negotiation finished successfully) [connect socket]
===> Original server certificate:
Subject DN: /C=CN/ST=Zhejiang/L=Hangzhou/O=NetEase (Hangzhou) Network Co., Ltd/OU=Mail Dept./CN=*.126.com
Common Names: *.126.com/*.126.com/126.com
Fingerprint: cf:7f:94:85:dd:c0:cc:08:94:a0:89:46:b1:d5:c6:32:78:31:14:85
SSL_free() in state 00000003 = 0003 = SSLOK  (SSL negotiation finished successfully) [connect socket]
tcp [192.168.1.101]:49254 [220.181.12.206]:80
SNI peek: [mail.126.com] [complete]
Attempt reuse dst SSL session
Connecting to [220.181.15.150]:443
===> Original server certificate:
Subject DN: /C=CN/ST=Zhejiang/L=Hangzhou/O=NetEase (Hangzhou) Network Co., Ltd/OU=Mail Dept./CN=*.126.com
Common Names: *.126.com/*.126.com/126.com
Fingerprint: cf:7f:94:85:dd:c0:cc:08:94:a0:89:46:b1:d5:c6:32:78:31:14:85
SNI peek: [mail.126.com] [complete]
Attempt reuse dst SSL session
Connecting to [220.181.15.150]:443
SSL_free() in state 00000003 = 0003 = SSLOK  (SSL negotiation finished successfully) [connect socket]
===> Original server certificate:
Subject DN: /C=CN/ST=Zhejiang/L=Hangzhou/O=NetEase (Hangzhou) Network Co., Ltd/OU=Mail Dept./CN=*.126.com
Common Names: *.126.com/*.126.com/126.com
Fingerprint: cf:7f:94:85:dd:c0:cc:08:94:a0:89:46:b1:d5:c6:32:78:31:14:85
SNI peek: [n/a] [complete]
Attempt reuse dst SSL session
Connecting to [220.181.15.150]:443
SSL_free() in state 00000003 = 0003 = SSLOK  (SSL negotiation finished successfully) [connect socket]
===> Original server certificate:
Subject DN: /C=CN/ST=Zhejiang/L=Hangzhou/O=NetEase (Hangzhou) Network Co., Ltd/OU=Mail Dept./CN=*.126.com
Common Names: *.126.com/*.126.com/126.com
Fingerprint: cf:7f:94:85:dd:c0:cc:08:94:a0:89:46:b1:d5:c6:32:78:31:14:85
SSL_free() in state 00000003 = 0003 = SSLOK  (SSL negotiation finished successfully) [connect socket]
SNI peek: [fe2.update.microsoft.com] [complete]
Connecting to [65.55.138.112]:443
===> Original server certificate:
Subject DN: /C=US/ST=Washington/L=Redmond/O=Microsoft/OU=WUPDS/CN=fe2.update.microsoft.com
Common Names: fe2.update.microsoft.com
Fingerprint: 5d:71:ab:ea:0d:0a:30:5c:23:77:28:a8:c3:ab:09:87:2a:73:36:ae
SNI peek: [fe2.update.microsoft.com] [complete]
Attempt reuse dst SSL session
Connecting to [65.55.138.112]:443
===> Original server certificate:
Subject DN: /C=US/ST=Washington/L=Redmond/O=Microsoft/OU=WUPDS/CN=fe2.update.microsoft.com
Common Names: fe2.update.microsoft.com
Fingerprint: 5d:71:ab:ea:0d:0a:30:5c:23:77:28:a8:c3:ab:09:87:2a:73:36:ae
SNI peek: [fe2.update.microsoft.com] [complete]
Attempt reuse dst SSL session
Connecting to [65.55.138.112]:443
===> Original server certificate:
Subject DN: /C=US/ST=Washington/L=Redmond/O=Microsoft/OU=WUPDS/CN=fe2.update.microsoft.com
Common Names: fe2.update.microsoft.com
Fingerprint: 5d:71:ab:ea:0d:0a:30:5c:23:77:28:a8:c3:ab:09:87:2a:73:36:ae

**Comment by kickwindbg** [comment]
My  intention is to use the server certificate signed by CA i created not generate by the sslsplit
but the sslsplit will generate a server certificate as the forged certificate  not the server certificate i created.  
i try every paramens combination i can   but not work

BTW the connection is TLSv1.2 and  have SNI in the client_hello extension


the reply from Miroslav Stampar who create the issue 20 give me such explain 

It was a long time ago, but I believe that something along these lines worked:

1) openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 1826
2) cat key.pem cert.pem > ./certs/facebook.pem       # for example
3) sslsplit... -P -t certs...

the -P can hold the connection but just passthrough,  not my intention

**Comment by droe** [comment]
The certificate you generate uses the Common Name "test", i.e. it matches a hostname of "test":

    Targets for '/tmp/sslsplit/cert/ca.pem': 'test'
    Targets for '/tmp/sslsplit/cert/server.pem': 'test'

Since you are not connecting to a host named "test", sslsplit has no matching certificate to offer to the client.

If you want to use `-t`, you need certificates that match the hostname you are connecting to (subject CN or subjectAlternativeName extension). See the respective section on `-t` in the manual page:

       -t certdir
              Use  private  key,  certificate  and  certificate chain from PEM
              files in certdir for sites matching the respective common names,
              instead  of  using certificates forged on-the-fly.  A single PEM
              file must contain a single private key, a single certificate and
              optionally  intermediate and root CA certificates to use as cer-
              tificate chain.  If -c and -k are also given, certificates  will
              be forged on-the-fly for sites matching none of the certificates
              loaded from certdir.  Otherwise, connections  matching  no  cer-
              tificate  will  be  dropped,  or  if -P is given, passed through
              without splitting SSL/TLS.
