### ISSUE TITLE
HTTP/2

### ISSUE THREAD

**Issue by emrahayanoglu** [droe/sslsplit#89]
I think latest version of the sslsplit doesn't support HTTP/2 protocol. Has it already planned to integrate HTTP/2 within sslsplit or not?

**Comment by droe** [comment]
No plans as of yet, happy to take patches.

**Comment by droe** [comment]
To be more specific as to current HTTP/2 support in SSLsplit:

-   HTTP/2 over TLS (h2)
    -   with `ssl`: produces binary HTTP/2 logs; no header mangling (compression, HPKP et al); no OCSP denial
    -   with `https`: downgrades to HTTP/1 by way of not indicating HTTP/2 support in TLS NPN/ALPN
-   HTTP/2 over TCP (h2c):
    -   with `tcp`: produces binary HTTP/2 logs; no header mangling or OCSP denial
    -   with `http`: unknown behaviour - HTTP/2 upgrade mechanism currently not suppressed - may likely result in problems when `http` parser attempts to parse HTTP/2 as HTTP/1 after a successful upgrade.

**Comment by emrahayanoglu** [comment]
Actually, my goal is to sniff the HTTP/2 packages over TLS with SSL for a research.

Nowadays, if I know correctly, most servers support both HTTP/1.1 and HTTP/2 over TLS with SSL. Therefore, it is not a problem at the moment, but it would be good feature for the future.

Anyway, if I have time, i'd like to participate in integrating HTTP/2 to sslsplit.

**Comment by droe** [comment]
With #91 implemented, current HTTP/2 support in SSLsplit is now:
-   HTTP/2 over TLS (h2)
  -   with `ssl` proxyspec: produces binary HTTP/2 logs; no header mangling (compression, HPKP et al); no OCSP denial
  -   with `https` proxyspec: downgrades to HTTP/1 by way of not indicating HTTP/2 support in TLS NPN/ALPN
-   HTTP/2 over TCP (h2c):
  -   with `tcp` proxyspec: produces binary HTTP/2 logs; no header mangling or OCSP denial
  -   with `http` proxyspec: downgrades to HTTP/1 by way of suppressing `Upgrade:` headers

**Comment by droe** [comment]
May make #62 obsolete.

**Comment by droe** [comment]
- [ ] Wait for #161 to be implemented, especially the proxy core refactoring
- [ ] Implement HTTP/2 protocol (possibly using a library, if feasible)
- [ ] Implement all upgrade paths to HTTP/2
- [ ] Adjust logging for new HTTP/2 concepts
- [ ] Test on different platforms and with different browsers/clients
