### ISSUE TITLE
Sign certificates using sha256 instead of sha1

### ISSUE THREAD

**Issue by scotloach** [droe/sslsplit#90]
Modern browsers want certs to be signed using sha-256.

I was able to get this to work by simply changing "EVP_sha1()" to "EVP_sha256()" on this line:
https://github.com/droe/sslsplit/blob/master/ssl.c#L825

But I expect a proper fix will have to do some more work to determine which algorithm to used based on what the openssl library supports and possibly based on user configuration.

**Comment by droe** [comment]
This has been fixed in 3da7407 in the `develop` branch; also see #83 for related documentation and test suite changes.
