### ISSUE TITLE
'Error creating SSL' for SSL Passthrough with -t and empty directory

### ISSUE THREAD

**Issue by xelalexv** [droe/sslsplit#92]
I'm trying to set up sslsplit as a transparent proxy for HTTP and HTTPS (passthrough only). Setup has two machines, client and proxy. Proxy is set as default gateway on client. On proxy, I enabled IP forwarding and added to iptables: 

```bash
sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080
sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 443 -j REDIRECT --to-port 8443
```

I'm starting sslsplit like this:

```bash
./sslsplit -D -t ./certdir/ -P https 0.0.0.0 8443 http 0.0.0.0 8080
```
```certdir``` is empty so that all HTTPS is passed through. Works so far for HTTP, but no joy with HTTPS. When requesting https://www.google.de with FF on client:

```log
SSLsplit 0.4.11 (built 2015-04-25)
Copyright (c) 2009-2014, Daniel Roethlisberger <daniel@roe.ch>
http://www.roe.ch/SSLsplit
Build info: V:GIT
Features: -DHAVE_NETFILTER
NAT engines: netfilter* tproxy
netfilter: IP_TRANSPARENT SOL_IPV6 !IPV6_ORIGINAL_DST
Local process info support: no
compiled against OpenSSL 1.0.1f 6 Jan 2014 (1000106f)
rtlinked against OpenSSL 1.0.1f 6 Jan 2014 (1000106f)
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
Using SSL_MODE_RELEASE_BUFFERS
SSL/TLS protocol availability: ssl3 tls10 tls11 tls12 
SSL/TLS algorithm availability: RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.0.21-stable
rtlinked against libevent 2.0.21-stable
4 CPU cores detected
SSL/TLS protocol: negotiate
proxyspecs:
- [0.0.0.0]:8080 tcp http netfilter
- [0.0.0.0]:8443 ssl http netfilter
No CA loaded.
Using libevent backend 'epoll'
Event base supports: edge yes, O(1) yes, anyfd no
Inserted events:
  0x250bd20 [fd 6] Read Persist
  0x250c330 [fd 7] Read Persist
  0x250c410 [fd 8] Read Persist
  0x250bb58 [fd 5] Read Persist
  0x250c7d0 [fd 3] Signal Persist
  0x250ca10 [fd 1] Signal Persist
  0x250cb40 [fd 2] Signal Persist
  0x250cc70 [fd 13] Signal Persist
Initialized 8 connection handling threads
Started 8 connection handling threads
Starting main event loop.
SNI peek: [www.google.de] [complete]
Error creating SSL
SNI peek: [www.google.de] [complete]
Error creating SSL
SNI peek: [www.google.de] [complete]
Error creating SSL
SNI peek: [www.google.de] [complete]
Error creating SSL
SNI peek: [www.google.de] [complete]
Error creating SSL
SNI peek: [www.google.de] [complete]
Error creating SSL
SNI peek: [www.google.de] [complete]
Error creating SSL
SNI peek: [www.google.de] [complete]
Error creating SSL
SNI peek: [www.google.de] [complete]
Error creating SSL
SNI peek: [www.google.de] [complete]
Error creating SSL
```

FF on client says "Secure connection failed, connection to server was reset while page was loading". Not sure why sslsplit would want to create an SSL session when it's supposed to only do passthrough. Hope I'm not doing anything wrong. 

BTW, both machines run Ubuntu 14.04. sslsplit was built from git repo.

**Comment by droe** [comment]
From your logs it does look like a bug. Would you be able to test the latest `develop` branch too? i.e. `git checkout develop; make clean; make; make test` and then retry if that still does not work?

**Comment by xelalexv** [comment]
I tried that, but still the same behaviour. I looked around a bit, and what happens is this: The call to  ```SSL_CTX_new``` in ```pxy_dstssl_create``` returns ```NULL```, and apparently the cause is that the SSL library is not initialized. So, just to poke around a bit, I added ```ssl_init()``` to ```main.c```:

```diff
@@ -865,6 +865,8 @@ main(int argc, char *argv[])
                sys_dir_eachfile(opts->tgcrtdir, main_loadtgcrt, opts);
        }
 
+       ssl_init();
+       
        /* Detach from tty; from this point on, only canonicalized absolute
         * paths should be used (-j, -F, -S). */
        if (opts->detach) {
```
And with that, passthrough for HTTPS now works :-) Couldn't figure out though why init isn't called in the first place.

**Comment by droe** [comment]
I suspect that init is not called because in the empty directory case no certificate loading occurs at all, and thus no init, since that is done implicitly from the ssl_* helper functions. Will look into it, thanks.

**Comment by droe** [comment]
I believe this has been fixed, closing the issue. Thanks for the bug report!
