### ISSUE TITLE
Compile issue Mac OS X 10.10.3

### ISSUE THREAD

**Issue by jvilhuber** [droe/sslsplit#96]
I'm seeing this from a plain 'make':
```
cc -L/opt/local /usr/lib -L/opt/local/lib -o sslsplit base64.o cache.o cachedsess.o cachefkcrt.o cachemgr.o cachessess.o cachetgcrt.o cert.o dynbuf.o log.o logbuf.o logger.o main.o nat.o opts.o proc.o proxy.o pxyconn.o pxysslshut.o pxythrmgr.o ssl.o sys.o thrqueue.o url.o util.o version.o -lssl -lcrypto -lz -levent -levent_openssl -levent_pthreads
ld: can't map file, errno=22 file '/usr/lib' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sslsplit] Error 1
```
If I remove the `/usr/lib` (notably without a -L), it compiles and runs fine.

**Comment by jvilhuber** [comment]
Darwin NachoPro.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

**Comment by jvilhuber** [comment]
Also, on the lua branch, I'm getting an error:
```
GNUmakefile:54: *** unterminated call to function `shell': missing `)'.  Stop.
```

Let me know what information I can gather.

**Comment by droe** [comment]
The last issue with the make file quoting is fixed both in the develop and master branches (0.4.11 release), but was not merged into the (purely experimental) lua branch so far.

The first issue looks like a bug in the make file that only manifests itself when pkg-config is unavailable and a dependency is autodetected in multiple locations, resulting in e.g. `OPENSSL_BASE=/opt/local /usr` which the rest of the make file cannot handle properly.

Workaround is to either make sure pkg-config is available (possibly setting PKGCONFIG manually) or manually set OPENSSL_BASE to either /opt/local or /usr, depending on which OpenSSL you want to use (make sure to use the same one your run-time linker will pull in when running the sslsplit binary; check with `sslsplit -V`).

**Comment by droe** [comment]
I believe this should be fixed, closing the issue.
