### ISSUE TITLE
Extract gzip data from log files

### ISSUE THREAD

**Issue by DigiAngel** [droe/sslsplit#97]
Topic says it...most of the time my log files are gzipped...and I've never found a way to extract the content.  Does anyone have a way to do this?

**Comment by droe** [comment]
Try using the `http` and `https` proxyspecs. Then the compression should be downgraded to uncompressed and you should not see any HTTP compressed data. If you use the `tcp` and `ssl` proxyspecs, there is no protocol decoding and hence no downgrading. If the manual page is unclear on this, please let me know how it can be improved.

**Comment by DigiAngel** [comment]
Thanks for that information....I'll give that a test this week and report my results.

**Comment by DigiAngel** [comment]
Yea that totally worked....I had been using ssl.  Thanks so much!
