### ISSUE TITLE
crashes after connecting using OpenSSL 0.9.8zd

### ISSUE THREAD

**Issue by clayg** [droe/sslsplit#99]
I'm trying to debug ssl requests (binary protocol not http) from a local application that I don't have control over.

Everything is running on mac os x 10.10

When I start sslsplit and try to connect to it - sslsplit dies unexpectedly:

    $ sudo ./sslsplit -P -D -l connections.log -k ca.key -c ca.crt ssl 0.0.0.0 8181 
    Generated RSA key for leaf certs.
    SSLsplit 0.4.11 (built 2015-06-11)
    Copyright (c) 2009-2014, Daniel Roethlisberger <daniel@roe.ch>
    http://www.roe.ch/SSLsplit
    Build info: OSX:10.10.3 XNU:2782.1.97:fallback:2782.20.48 V:GIT
    Features: -DHAVE_DARWIN_LIBPROC -DHAVE_PF
    NAT engines: pf*
    Local process info support: yes (Darwin libproc)
    compiled against OpenSSL 0.9.8zd 8 Jan 2015 (9081df)
    rtlinked against OpenSSL 0.9.8zd 8 Jan 2015 (9081df)
    TLS Server Name Indication (SNI) supported
    OpenSSL is thread-safe without THREADID
    Not using SSL_MODE_RELEASE_BUFFERS
    SSL/TLS protocol availability: ssl3 tls10 
    SSL/TLS algorithm availability: RSA DSA ECDSA DH !ECDH EC
    OpenSSL option availability: !SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
    compiled against libevent 2.0.22-stable
    rtlinked against libevent 2.0.22-stable
    8 CPU cores detected
    SSL/TLS protocol: negotiate
    proxyspecs:
    - [0.0.0.0]:8181 ssl plain pf
    Loaded CA: '/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd'
    NAT engine preinit 'pf'
    Using libevent backend 'kqueue'
    Event base supports: edge yes, O(1) yes, anyfd yes
    NAT engine init 'pf'
    Inserted events:
      0x7fac49500c68 [fd 7] Read Persist
      0x7fac49501490 [fd 9] Read Persist
      0x7fac49501520 [fd 3] Signal Persist
      0x7fac495011c0 [fd 1] Signal Persist
      0x7fac49501250 [fd 2] Signal Persist
      0x7fac495012e0 [fd 13] Signal Persist
    Initialized 16 connection handling threads
    Started 16 connection handling threads
    Starting main event loop.
    SNI peek: [n/a] [complete]
    Connecting to [XXX.XXX.XXX.XXX]:8181
    $ echo $?
    139

From the client side I see:

    $ openssl s_client -connect XXX.XXX.XXX.XXX:8181
    CONNECTED(00000003)
    1226:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:/SourceCache/OpenSSL098/OpenSSL098-52.20.2/src/ssl/s23_lib.c:185:

I've tried to configured port forwarding rules based on http://serverfault.com/questions/421261/os-x-10-8-redirecting-locally-initiated-ssh-connections-to-localhost22 with the additional restriction that only applications started as my user (openssl in this example) will have outbound connections on 8181 passed through loopback and redirected to localhost:

    rdr pass log on lo0 proto tcp from en0 to any port 8181 -> 127.0.0.1
    pass out on en0 route-to lo0 inet proto tcp from en0 to any port 8181 keep state user clayg

In this manner I seem to have avoided sslsplit (started as root with sudo) having connections routed back to itself - but I'm not sure what to do with this unexpected abort?  The file `connections.log` is empty.

Please advise.

**Comment by droe** [comment]
Would you be able to provide me with a backtrace to know where it crashes? i.e. run sslsplit from gdb and attach the output of `bt full` to this issue, or let your system produce a core file by running `ulimit -c unlimited` in a shell before running sslsplit and then run gdb on the core file.

A backtrace is most useful if you compile SSLsplit with debug symbols (i.e. from a git checkout).

The other thing that would help is the output of failed unit tests (`make test`), if any of them fail.

**Comment by clayg** [comment]
Thanks for the suggestions.

Tests seem to pass.  Please let me know if I can make the gdb output more useful.

https://gist.github.com/clayg/9679f16c6f6f6dced26d

**Comment by droe** [comment]
The crash is within OpenSSL, not within SSLsplit. Two possibilities: SSLsplit does not set up old-style thread safety properly for OpenSSL 0.9.8, or this is a bug in OpenSSL 0.9.8. I suspect the latter.

Does the crash only happen when you connect to that specific server or for all servers you connect to?

Otherwise try using a more recent version of OpenSSL, I'd recommend the latest 1.0.2 series release. You will want that anyway to get support for modern versions of TLS and modern cipher suites.

**Comment by clayg** [comment]
Newer version of openssl did the trick - good call.

I installed with brew and ran make clean; make - worked a treat.

Thanks
